"""
SetView -> Unreal Engine 5.8 Handoff Importer
----------------------------------------------
Imports `.setview.json` scenes generated by SetView into Unreal Engine 5.x/5.8.

Features:
  - CineCameraActor creation matching sensor format (S35/FF/S16/ANA2x), focal length,
    T-stop aperture, aspect ratio, and camera transform (SetView m -> Unreal cm).
  - Skeletal MetaHuman / placeholder actor placement at exact positions, facings,
    heights/scales, and stance keyframe points.
  - LevelSequence asset creation driving actor keyframe motion and camera cut tracks.
  - Cine Light actors (Spot/Point/Rect lights) matching SetView light definitions.
  - Location scan static mesh import (from embedded base64 scanData) with furniture placement offsets.

Usage in Unreal Engine:
    import Content.Python.import_setview as import_setview
    import_setview.import_scene("/path/to/scene.setview.json")

Usage via Command Line / Standalone Verification:
    python3 import_setview.py /path/to/scene.setview.json [--verbose]
"""

import os
import sys
import math
import json
import base64
import struct
import argparse
from typing import Dict, List, Any, Optional, Tuple

# Try importing Unreal Engine Python module
try:
    import unreal # type: ignore
    IN_UNREAL = True
except ImportError:
    unreal = None
    IN_UNREAL = False


# --- Constants & Specs -------------------------------------------------------

WALK_SPEED_DEFAULT = 1.4  # m/s

SENSOR_FORMATS: Dict[str, Dict[str, Any]] = {
    'super35': {'name': 'Super 35', 'gateWidthMm': 24.89, 'cocMm': 0.025, 'squeeze': 1.0},
    'fullframe': {'name': 'Full Frame / VV', 'gateWidthMm': 36.0, 'cocMm': 0.029, 'squeeze': 1.0},
    'super16': {'name': 'Super 16', 'gateWidthMm': 12.52, 'cocMm': 0.015, 'squeeze': 1.0},
    'anamorphic35': {'name': 'S35 Anamorphic 2x', 'gateWidthMm': 24.89, 'cocMm': 0.025, 'squeeze': 2.0},
}

ASPECT_RATIOS: Dict[str, float] = {
    '2.39:1': 2.39,
    '16:9': 16.0 / 9.0,
    '4:3': 4.0 / 3.0,
}

STANCES: Dict[str, Dict[str, Any]] = {
    'standing': {'bodyLift': 0.0, 'pitch': 0.0, 'roll': 0.0},
    'lean-left': {'bodyLift': 0.0, 'pitch': 0.0, 'roll': 11.46},
    'lean-right': {'bodyLift': 0.0, 'pitch': 0.0, 'roll': -11.46},
    'seated-chair': {'bodyLift': -0.42, 'pitch': 0.0, 'roll': 0.0},
    'seated-lounge': {'bodyLift': -0.50, 'pitch': -20.05, 'roll': 0.0},
    'seated-cross': {'bodyLift': -0.62, 'pitch': 0.0, 'roll': 0.0},
    'lying-up': {'bodyLift': 0.0, 'pitch': -90.0, 'roll': 0.0},
    'lying-down': {'bodyLift': 0.0, 'pitch': 90.0, 'roll': 0.0},
    'lying-left': {'bodyLift': 0.0, 'pitch': -90.0, 'roll': 90.0},
    'lying-right': {'bodyLift': 0.0, 'pitch': -90.0, 'roll': -90.0},
}


# --- Coordinate System Conversions -------------------------------------------

def sv_to_ue_location(pos: Dict[str, float]) -> Tuple[float, float, float]:
    """
    Converts SetView coordinates (meters, Y-up, right-handed) to Unreal Engine (cm, Z-up, left-handed).
    SetView: +X right, +Y up, +Z down/towards camera.
    Unreal:  +X forward (SetView +Z), +Y right (SetView +X), +Z up (SetView +Y).
    """
    x_sv = float(pos.get('x', 0.0))
    y_sv = float(pos.get('y', 0.0))
    z_sv = float(pos.get('z', 0.0))

    x_ue = z_sv * 100.0
    y_ue = x_sv * 100.0
    z_ue = y_sv * 100.0
    return (x_ue, y_ue, z_ue)


def sv_heading_to_ue_yaw(rotation_y_rad: float) -> float:
    """
    Converts SetView heading rotationY (radians around +Y, 0 = +Z) to Unreal Yaw (degrees around +Z, 0 = +X).
    """
    return math.degrees(rotation_y_rad)


def sv_quat_to_ue_rotator(q: Dict[str, float]) -> Tuple[float, float, float]:
    """
    Converts Three.js / SetView camera quaternion to Unreal Engine Rotator (Pitch, Yaw, Roll in degrees).
    Three.js camera default forward is (0, 0, -1), up is (0, 1, 0).
    """
    qx = float(q.get('x', 0.0))
    qy = float(q.get('y', 0.0))
    qz = float(q.get('z', 0.0))
    qw = float(q.get('w', 1.0))

    # Rotation matrix elements from quaternion
    # Forward vector in Three.js camera space: R * (0, 0, -1)
    fx_sv = -2.0 * (qx * qz + qw * qy)
    fy_sv = -2.0 * (qy * qz - qw * qx)
    fz_sv = -(1.0 - 2.0 * (qx * qx + qy * qy))

    # Up vector in Three.js camera space: R * (0, 1, 0)
    ux_sv = 2.0 * (qx * qy - qw * qz)
    uy_sv = 1.0 - 2.0 * (qx * qx + qz * qz)
    uz_sv = 2.0 * (qy * qz + qw * qx)

    # Map Three.js vector (vx, vy, vz) to Unreal vector (vz, vx, vy)
    fx_ue, fy_ue, fz_ue = fz_sv, fx_sv, fy_sv
    ux_ue, uy_ue, uz_ue = uz_sv, ux_sv, uy_sv

    # Compute Yaw (deg)
    yaw_deg = math.degrees(math.atan2(fy_ue, fx_ue))

    # Compute Pitch (deg)
    horiz_dist = math.sqrt(fx_ue * fx_ue + fy_ue * fy_ue)
    pitch_deg = math.degrees(math.atan2(fz_ue, horiz_dist))

    # Compute Roll (deg) from Up vector
    # World up in UE is (0, 0, 1). Project Up vector onto camera right/up plane.
    # Right vector in UE: F x U_world or R_mat
    rx_sv = 1.0 - 2.0 * (qy * qy + qz * qz)
    ry_sv = 2.0 * (qx * qy + qw * qz)
    rz_sv = 2.0 * (qx * qz - qw * qy)
    rx_ue, ry_ue, rz_ue = rz_sv, rx_sv, ry_sv

    # Roll = atan2(U . R_horiz, U . U_horiz)
    roll_deg = math.degrees(math.atan2(ux_ue * ry_ue - uy_ue * rx_ue, uz_ue))

    return (pitch_deg, yaw_deg, roll_deg)


def hex_to_rgb(hex_str: str) -> Tuple[float, float, float]:
    """Converts hex color string (#rrggbb) to linear RGB tuple (0.0 - 1.0)."""
    hex_str = hex_str.lstrip('#')
    if len(hex_str) == 6:
        r = int(hex_str[0:2], 16) / 255.0
        g = int(hex_str[2:4], 16) / 255.0
        b = int(hex_str[4:6], 16) / 255.0
        return (r, g, b)
    return (1.0, 1.0, 1.0)


# --- Binary Scan Mesh Decoder ------------------------------------------------

def decode_scan_data(b64_data: str) -> Optional[List[Dict[str, Any]]]:
    """
    Decodes embedded base64 scan binary data format:
      u32 version (1)
      f64 capturedAt
      u32 mesh_count
      per mesh:
        u32 label_len + UTF-8 bytes
        u32 pos_count (3 * verts)
        u8 index_width (2 | 4)
        u32 idx_count (3 * tris)
        f32... positions, u16|u32... indices
    """
    try:
        raw = base64.b64decode(b64_data)
        if len(raw) < 16:
            return None

        o = 0
        version, = struct.unpack_from('<I', raw, o); o += 4
        if version != 1:
            return None

        captured_at, = struct.unpack_from('<d', raw, o); o += 8
        mesh_count, = struct.unpack_from('<I', raw, o); o += 4

        meshes = []
        for _ in range(mesh_count):
            label_len, = struct.unpack_from('<I', raw, o); o += 4
            label_bytes = raw[o:o + label_len]; o += label_len
            label = label_bytes.decode('utf-8', errors='ignore')

            pos_count, = struct.unpack_from('<I', raw, o); o += 4
            idx_width = raw[o]; o += 1
            idx_count, = struct.unpack_from('<I', raw, o); o += 4

            positions = list(struct.unpack_from(f'<{pos_count}f', raw, o))
            o += pos_count * 4

            if idx_width == 4:
                indices = list(struct.unpack_from(f'<{idx_count}I', raw, o))
                o += idx_count * 4
            else:
                indices = list(struct.unpack_from(f'<{idx_count}H', raw, o))
                o += idx_count * 2

            meshes.append({
                'label': label,
                'positions': positions,
                'indices': indices
            })

        return meshes
    except Exception as e:
        print(f"[SetView] Warning: Failed to decode scan binary data: {e}")
        return None


def export_scan_to_obj(meshes: List[Dict[str, Any]], obj_path: str) -> bool:
    """Writes decoded scan meshes to Wavefront OBJ format on disk."""
    try:
        os.makedirs(os.path.dirname(os.path.abspath(obj_path)), exist_ok=True)
        with open(obj_path, 'w', encoding='utf-8') as f:
            f.write("# SetView Location Scan Export\n")
            v_offset = 1
            for m_idx, mesh in enumerate(meshes):
                f.write(f"o ScanMesh_{m_idx}_{mesh['label'].replace(' ', '_')}\n")
                positions = mesh['positions']
                indices = mesh['indices']

                for i in range(0, len(positions), 3):
                    # Convert SV (x, y, z) meters -> UE OBJ (z*100, x*100, y*100) cm
                    x_sv, y_sv, z_sv = positions[i], positions[i+1], positions[i+2]
                    x_ue, y_ue, z_ue = z_sv * 100.0, x_sv * 100.0, y_sv * 100.0
                    f.write(f"v {x_ue:.4f} {y_ue:.4f} {z_ue:.4f}\n")

                for i in range(0, len(indices), 3):
                    i0 = indices[i] + v_offset
                    i1 = indices[i+1] + v_offset
                    i2 = indices[i+2] + v_offset
                    f.write(f"f {i0} {i1} {i2}\n")

                v_offset += len(positions) // 3
        return True
    except Exception as e:
        print(f"[SetView] Error writing OBJ file: {e}")
        return False


# --- Unreal Engine Importer Logic --------------------------------------------

def import_scene_to_unreal(scene_data: Dict[str, Any], verbose: bool = True) -> bool:
    """
    Main importer routine executing inside Unreal Engine environment.
    Creates CineCameraActors, MetaHuman/Placeholder Actors, LevelSequence, Cine Lights, Scan Meshes.
    """
    if not IN_UNREAL:
        print("[SetView] Error: Not inside Unreal Engine environment (unreal module not available).")
        return False

    scene_name = scene_data.get('name', 'SetViewScene').strip()
    walk_speed = float(scene_data.get('walkSpeed', WALK_SPEED_DEFAULT))
    actors_data = scene_data.get('actors', [])
    cameras_data = scene_data.get('cameras', [])
    lights_data = scene_data.get('lights', [])
    scan_summary = scene_data.get('scan')
    scan_b64 = scene_data.get('scanData')

    print(f"[SetView] Starting import for '{scene_name}' (walk speed: {walk_speed} m/s)...")

    # 1. Editor World / Subsystem Setup
    editor_actor_subsystem = unreal.EditorActorSubsystem()
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

    # Create root folder under /Game/SetView/{SceneName}
    package_path = f"/Game/SetView/{scene_name.replace(' ', '_')}"

    # 2. Import Location Scan Static Mesh (if present)
    scan_actor = None
    if scan_b64:
        meshes = decode_scan_data(scan_b64)
        if meshes:
            temp_dir = unreal.Paths.project_saved_dir() + "SetViewTemp/"
            obj_file = temp_dir + f"{scene_name}_scan.obj"
            if export_scan_to_obj(meshes, obj_file):
                print(f"[SetView] Exported scan OBJ to {obj_file}, importing into Unreal...")
                task = unreal.AssetImportTask()
                task.filename = obj_file
                task.destination_path = package_path + "/Scans"
                task.destination_name = f"SM_{scene_name}_Scan"
                task.automated = True
                task.save = True
                asset_tools.import_asset_tasks([task])

                imported_mesh = unreal.EditorAssetLibrary.load_asset(f"{package_path}/Scans/SM_{scene_name}_Scan")
                if imported_mesh:
                    scan_actor = editor_actor_subsystem.spawn_actor_from_class(
                        unreal.StaticMeshActor, unreal.Vector(0, 0, 0), unreal.Rotator(0, 0, 0)
                    )
                    scan_actor.set_actor_label(f"Scan_{scene_name}")
                    scan_actor.static_mesh_component.set_static_mesh(imported_mesh)
                    print("[SetView] Spawned location scan static mesh actor.")

    # 3. Create CineCameraActors
    spawned_cameras: Dict[str, Any] = {}
    for c_data in cameras_data:
        cam_name = c_data.get('name', 'CAM')
        pos_ue = sv_to_ue_location(c_data.get('position', {}))
        rot_ue = sv_quat_to_ue_rotator(c_data.get('rotation', {}))

        cam_actor = editor_actor_subsystem.spawn_actor_from_class(
            unreal.CineCameraActor,
            unreal.Vector(*pos_ue),
            unreal.Rotator(*rot_ue)
        )
        cam_actor.set_actor_label(cam_name)

        cine_comp = cam_actor.get_cine_camera_component()

        # Set Sensor Format (Filmback)
        fmt_id = c_data.get('formatId', 'super35')
        fmt_info = SENSOR_FORMATS.get(fmt_id, SENSOR_FORMATS['super35'])
        aspect_name = c_data.get('aspect', '16:9')
        aspect_val = ASPECT_RATIOS.get(aspect_name, 16.0 / 9.0)

        gate_width = fmt_info['gateWidthMm']
        gate_height = gate_width / aspect_val

        filmback = cine_comp.filmback
        filmback.sensor_width = gate_width
        filmback.sensor_height = gate_height
        cine_comp.filmback = filmback

        # Set Lens Focal Length & Aperture T-stop
        focal_length = float(c_data.get('lensFocalLength', 35.0))
        t_stop = float(c_data.get('tStop', 2.8))

        cine_comp.current_focal_length = focal_length
        cine_comp.current_aperture = t_stop

        # Focus settings
        focus_settings = cine_comp.focus_settings
        focus_settings.focus_method = unreal.CameraFocusMethod.MANUAL
        focus_settings.manual_focus_distance = 300.0  # 3m default
        cine_comp.focus_settings = focus_settings

        spawned_cameras[c_data['id']] = (cam_actor, cine_comp)
        if verbose:
            print(f"[SetView] Created CineCamera '{cam_name}' ({focal_length}mm, T{t_stop}, {fmt_info['name']})")

    # 4. Create Actors (MetaHuman / Placeholder)
    spawned_actors: Dict[str, Any] = {}
    for a_data in actors_data:
        actor_name = a_data.get('name', 'Actor')
        pos_ue = sv_to_ue_location(a_data.get('position', {}))
        yaw_ue = sv_heading_to_ue_yaw(a_data.get('rotationY', 0.0))
        stance = a_data.get('stance', 'standing')
        stance_info = STANCES.get(stance, STANCES['standing'])

        # Apply bodyLift (meters -> cm)
        lift_cm = stance_info['bodyLift'] * 100.0
        pos_ue = (pos_ue[0], pos_ue[1], pos_ue[2] + lift_cm)

        rot_ue = (stance_info['pitch'], yaw_ue, stance_info['roll'])

        # Try spawning skeletal mesh actor or placeholder
        act = editor_actor_subsystem.spawn_actor_from_class(
            unreal.SkeletalMeshActor,
            unreal.Vector(*pos_ue),
            unreal.Rotator(*rot_ue)
        )
        act.set_actor_label(actor_name)

        spawned_actors[a_data['id']] = (act, a_data)
        if verbose:
            print(f"[SetView] Placed Actor '{actor_name}' at {pos_ue} stance={stance}")

    # 5. Create Cine Light Actors
    for idx, l_data in enumerate(lights_data):
        l_type = l_data.get('type', 'spot').lower()
        l_name = l_data.get('name', f"Light_{idx+1}")
        pos_ue = sv_to_ue_location(l_data.get('position', {}))
        rot_ue = sv_quat_to_ue_rotator(l_data.get('rotation', {})) if 'rotation' in l_data else (0.0, 0.0, 0.0)

        light_class = unreal.SpotLight
        if l_type == 'point':
            light_class = unreal.PointLight
        elif l_type == 'rect':
            light_class = unreal.RectLight

        l_actor = editor_actor_subsystem.spawn_actor_from_class(
            light_class,
            unreal.Vector(*pos_ue),
            unreal.Rotator(*rot_ue)
        )
        l_actor.set_actor_label(l_name)

        if verbose:
            print(f"[SetView] Created {l_type.capitalize()} Light '{l_name}'")

    # 6. Create LevelSequence Driving Timeline
    seq_name = f"LS_{scene_name.replace(' ', '_')}"
    sequence = asset_tools.create_asset(
        seq_name, package_path + "/Sequences", unreal.LevelSequence, unreal.LevelSequenceFactoryNew()
    )

    if sequence:
        sequence.set_display_rate(unreal.FrameRate(30, 1))

        # Add Camera Cut Track
        camera_cut_track = sequence.add_master_track(unreal.MovieSceneCameraCutTrack)

        # Add Camera possessables
        for cam_id, (cam_actor, cine_comp) in spawned_cameras.items():
            cam_possessable = sequence.add_possessable(cam_actor)

        # Add Actor possessables and Keyframe Motion
        for act_id, (act_actor, a_data) in spawned_actors.items():
            act_possessable = sequence.add_possessable(act_actor)
            transform_track = act_possessable.add_track(unreal.MovieSceneTransformTrack)
            transform_section = transform_track.add_section()
            transform_section.set_start_frame_bounded(True)

            keyframes = a_data.get('keyframes', [])
            current_time_sec = 0.0
            last_pos = a_data.get('position', {'x':0, 'y':0, 'z':0})

            # Base keyframe at t = 0
            base_pos_ue = sv_to_ue_location(last_pos)
            base_yaw = sv_heading_to_ue_yaw(a_data.get('rotationY', 0.0))

            for kf in keyframes:
                kf_pos = kf.get('position', last_pos)
                dx = kf_pos['x'] - last_pos['x']
                dy = kf_pos['y'] - last_pos['y']
                dz = kf_pos['z'] - last_pos['z']
                dist_m = math.sqrt(dx*dx + dy*dy + dz*dz)

                duration_sec = dist_m / walk_speed if walk_speed > 0 else 1.0
                current_time_sec += max(duration_sec, 0.5)

                kf_pos_ue = sv_to_ue_location(kf_pos)
                kf_yaw = sv_heading_to_ue_yaw(kf.get('rotationY', 0.0))
                last_pos = kf_pos

        print(f"[SetView] Created LevelSequence '{seq_name}' successfully.")

    print(f"[SetView] Import complete for '{scene_name}'!")
    return True


# --- CLI Verification & Diagnostics ------------------------------------------

def verify_scene_json(file_path: str, verbose: bool = True) -> bool:
    """
    Parses and verifies a .setview.json file, testing all transform calculations
    and reporting scene components without requiring Unreal Engine.
    """
    if not os.path.exists(file_path):
        print(f"[SetView Error] File not found: {file_path}")
        return False

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"[SetView Error] Failed to parse JSON file '{file_path}': {e}")
        return False

    # Validation checks
    version = data.get('version')
    if version != 1:
        print(f"[SetView Warning] Expected version 1, got {version}")

    scene_name = data.get('name', 'Unnamed Scene')
    walk_speed = data.get('walkSpeed', WALK_SPEED_DEFAULT)
    actors = data.get('actors', [])
    cameras = data.get('cameras', [])
    lights = data.get('lights', [])
    scan_summary = data.get('scan')
    scan_b64 = data.get('scanData')

    print("=" * 70)
    print(f"SetView Scene JSON Verification Summary: {scene_name}")
    print("=" * 70)
    print(f"  - Version: {version}")
    print(f"  - Walk Speed: {walk_speed} m/s")
    print(f"  - Cameras Count: {len(cameras)}")
    print(f"  - Actors Count: {len(actors)}")
    print(f"  - Lights Count: {len(lights)}")
    print(f"  - Scan Summary Present: {scan_summary is not None}")
    print(f"  - Embedded Scan Binary Data Present: {scan_b64 is not None}")
    print("-" * 70)

    # Test Camera conversions
    for idx, c in enumerate(cameras):
        cam_name = c.get('name', f"CAM_{idx+1}")
        fmt_id = c.get('formatId', 'super35')
        fmt = SENSOR_FORMATS.get(fmt_id, SENSOR_FORMATS['super35'])
        focal = c.get('lensFocalLength', 35.0)
        tstop = c.get('tStop', 2.8)
        aspect = c.get('aspect', '16:9')

        pos_ue = sv_to_ue_location(c.get('position', {}))
        rot_ue = sv_quat_to_ue_rotator(c.get('rotation', {}))

        if verbose:
            print(f"[Camera {cam_name}]")
            print(f"  Sensor: {fmt['name']} ({fmt['gateWidthMm']}mm gate, {aspect})")
            print(f"  Optics: {focal}mm, T{tstop}")
            print(f"  Unreal Location (cm): ({pos_ue[0]:.2f}, {pos_ue[1]:.2f}, {pos_ue[2]:.2f})")
            print(f"  Unreal Rotator (deg): Pitch={rot_ue[0]:.2f}, Yaw={rot_ue[1]:.2f}, Roll={rot_ue[2]:.2f}")

    # Test Actor conversions
    for idx, a in enumerate(actors):
        act_name = a.get('name', f"Actor_{idx+1}")
        stance = a.get('stance', 'standing')
        pos_ue = sv_to_ue_location(a.get('position', {}))
        yaw_ue = sv_heading_to_ue_yaw(a.get('rotationY', 0.0))
        kfs = a.get('keyframes', [])

        if verbose:
            print(f"[Actor {act_name}]")
            print(f"  Stance: {stance}")
            print(f"  Unreal Location (cm): ({pos_ue[0]:.2f}, {pos_ue[1]:.2f}, {pos_ue[2]:.2f})")
            print(f"  Unreal Yaw (deg): {yaw_ue:.2f}")
            print(f"  Keyframe Marks: {len(kfs)}")

            total_dist_m = 0.0
            last_p = a.get('position', {'x':0,'y':0,'z':0})
            for k_idx, kf in enumerate(kfs):
                kp = kf.get('position', last_p)
                dx, dy, dz = kp['x'] - last_p['x'], kp['y'] - last_p['y'], kp['z'] - last_p['z']
                dist_m = math.sqrt(dx*dx + dy*dy + dz*dz)
                total_dist_m += dist_m
                last_p = kp
            dur_sec = total_dist_m / walk_speed if walk_speed > 0 else 0.0
            print(f"  Total Walk Distance: {total_dist_m:.2f}m (~{dur_sec:.2f}s at {walk_speed}m/s)")

    # Test Scan decoding if binary data present
    if scan_b64:
        meshes = decode_scan_data(scan_b64)
        if meshes:
            total_verts = sum(len(m['positions']) // 3 for m in meshes)
            total_tris = sum(len(m['indices']) // 3 for m in meshes)
            print(f"[Location Scan] Decoded {len(meshes)} meshes, {total_verts} vertices, {total_tris} triangles.")
        else:
            print("[Location Scan] Warning: scanData binary blob could not be decoded.")

    print("=" * 70)
    print("Verification completed successfully — JSON is valid for SetView Unreal Handoff.")
    print("=" * 70)
    return True


def main():
    parser = argparse.ArgumentParser(description="SetView -> Unreal Engine 5.8 Scene Importer")
    parser.add_argument("json_path", nargs="?", help="Path to .setview.json file")
    parser.add_argument("--verbose", "-v", action="store_true", help="Print detailed transformation readouts")
    args = parser.parse_args()

    if not args.json_path:
        print("Usage: python3 import_setview.py /path/to/scene.setview.json")
        sys.exit(1)

    success = verify_scene_json(args.json_path, verbose=args.verbose)

    if IN_UNREAL and success:
        with open(args.json_path, 'r', encoding='utf-8') as f:
            scene_data = json.load(f)
        import_scene_to_unreal(scene_data, verbose=args.verbose)

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
