"""
SetView -> Unreal Engine 5.8 Handoff Importer
----------------------------------------------
Imports `.setview.json` scenes generated by SetView into Unreal Engine 5.x/5.8.

Features:
  - CineCameraActor creation matching sensor format (S35/FF/S16/ANA2x), focal length,
    T-stop aperture, aspect ratio, and camera transform (SetView m -> Unreal cm).
  - Skeletal MetaHuman / placeholder actor placement at exact positions, facings,
    heights/scales, and stance keyframe points.
  - LevelSequence asset creation driving actor keyframe motion and camera cut tracks.
  - Cine Light actors (Spot/Point/Rect lights) matching SetView light definitions.
  - Location scan static mesh import (from embedded base64 scanData) with furniture placement offsets.

Usage in Unreal Engine (Content/Python is on sys.path inside the editor):
    import import_setview
    import_setview.import_scene("/path/to/scene.setview.json")

Usage via Command Line / Standalone Verification:
    python3 import_setview.py /path/to/scene.setview.json [--verbose]
"""

import os
import sys
import math
import json
import base64
import struct
import argparse
from typing import Dict, List, Any, Optional, Tuple

# Try importing Unreal Engine Python module
try:
    import unreal # type: ignore
    IN_UNREAL = True
except ImportError:
    unreal = None
    IN_UNREAL = False


# --- Constants & Specs -------------------------------------------------------

WALK_SPEED_DEFAULT = 1.4  # m/s
ACTOR_HEIGHT_M_DEFAULT = 1.7
ACTOR_WIDTH_SCALE = 0.35
CYLINDER_ASSET = '/Engine/BasicShapes/Cylinder.Cylinder'
SEQUENCE_FPS = 30
MIN_SEGMENT_S = 0.4   # matches src/timeline.ts minimum per-segment duration
CAMERA_MOVE_SPEED = 1.0  # m/s previz dolly pace between camera keyframes

SENSOR_FORMATS: Dict[str, Dict[str, Any]] = {
    'super35': {'name': 'Super 35', 'gateWidthMm': 24.89, 'cocMm': 0.025, 'squeeze': 1.0},
    'fullframe': {'name': 'Full Frame / VV', 'gateWidthMm': 36.0, 'cocMm': 0.029, 'squeeze': 1.0},
    'super16': {'name': 'Super 16', 'gateWidthMm': 12.52, 'cocMm': 0.015, 'squeeze': 1.0},
    'anamorphic35': {'name': 'S35 Anamorphic 2x', 'gateWidthMm': 24.89, 'cocMm': 0.025, 'squeeze': 2.0},
}

ASPECT_RATIOS: Dict[str, float] = {
    '2.39:1': 2.39,
    '16:9': 16.0 / 9.0,
    '4:3': 4.0 / 3.0,
}

_HALF_PI = math.pi / 2.0

# Whole-body Euler applied about the feet origin, mirroring src/pose.ts `bodyRot`
# (Three.js Euler order 'XYZ', radians) plus the vertical lift in metres.
#
# These are stored as the SetView-side rotation rather than as pre-baked Unreal
# pitch/roll degrees on purpose. The baked table used to carry the wrong sign on
# BOTH pitch and roll -- an actor SetView showed lying on their back imported
# face-down, and every lean/roll came out mirrored -- because the degrees were
# hand-maintained and never revisited when the basis map was corrected to
# determinant -1. Deriving the rotator from these values through
# sv_direction_to_ue + ue_basis_to_rotator keeps exactly one definition of the
# handedness convention, so a stance cannot drift away from it again.
STANCES: Dict[str, Dict[str, Any]] = {
    'standing': {'bodyLift': 0.0, 'bodyRot': (0.0, 0.0, 0.0)},
    'lean-left': {'bodyLift': 0.0, 'bodyRot': (0.0, 0.0, 0.2)},
    'lean-right': {'bodyLift': 0.0, 'bodyRot': (0.0, 0.0, -0.2)},
    'seated-chair': {'bodyLift': -0.42, 'bodyRot': (0.0, 0.0, 0.0)},
    'seated-lounge': {'bodyLift': -0.50, 'bodyRot': (-0.35, 0.0, 0.0)},
    'seated-cross': {'bodyLift': -0.62, 'bodyRot': (0.0, 0.0, 0.0)},
    'lying-up': {'bodyLift': 0.0, 'bodyRot': (-_HALF_PI, 0.0, 0.0)},
    'lying-down': {'bodyLift': 0.0, 'bodyRot': (_HALF_PI, 0.0, 0.0)},
    'lying-left': {'bodyLift': 0.0, 'bodyRot': (-_HALF_PI, 0.0, _HALF_PI)},
    'lying-right': {'bodyLift': 0.0, 'bodyRot': (-_HALF_PI, 0.0, -_HALF_PI)},
}


# --- Coordinate System Conversions -------------------------------------------

SCALE_M_TO_CM = 100.0


def sv_direction_to_ue(v: Tuple[float, float, float]) -> Tuple[float, float, float]:
    """
    Maps a SetView direction vector into Unreal's axis convention (no unit scaling).

    SetView is right-handed (+X right, +Y up, camera looks down -Z); Unreal is
    left-handed (+X forward, +Y right, +Z up). A right-handed -> left-handed
    conversion REQUIRES a determinant -1 basis map, i.e. an odd number of axis
    negations: (x, y, z) -> (-z, x, y), matrix [[0,0,-1],[1,0,0],[0,1,0]].

    The determinant +1 permutation (x, y, z) -> (z, x, y) is a pure rotation. It
    looks self-consistent but produces a clean mirror image of the scene, which
    silently reverses every screen direction (and invalidates line-of-action /
    eyeline continuity).
    """
    return (-v[2], v[0], v[1])


def ue_direction_to_sv(v: Tuple[float, float, float]) -> Tuple[float, float, float]:
    """Inverse of sv_direction_to_ue: (x, y, z)_ue -> (y, z, -x)_sv."""
    return (v[1], v[2], -v[0])


def sv_to_ue_location(pos: Dict[str, float]) -> Tuple[float, float, float]:
    """
    Converts SetView coordinates (meters, Y-up, right-handed) to Unreal Engine (cm, Z-up, left-handed).
      x_ue = -z_sv * 100,  y_ue = x_sv * 100,  z_ue = y_sv * 100
    """
    x_sv = float(pos.get('x', 0.0))
    y_sv = float(pos.get('y', 0.0))
    z_sv = float(pos.get('z', 0.0))

    d = sv_direction_to_ue((x_sv, y_sv, z_sv))
    return (d[0] * SCALE_M_TO_CM, d[1] * SCALE_M_TO_CM, d[2] * SCALE_M_TO_CM)


def sv_heading_to_ue_yaw(rotation_y_rad: float) -> float:
    """
    Converts SetView heading rotationY (radians around +Y, 0 = +Z) to Unreal Yaw (degrees around +Z, 0 = +X).

    Under the determinant -1 map a SetView heading of 0 (facing +Z) points along
    Unreal -X, which is yaw 180; the sweep direction also reverses. Hence
    yaw = 180 - degrees(rotationY): 0 -> 180, 90 -> 90, 180 -> 0, 270 -> -90.
    """
    return 180.0 - math.degrees(float(rotation_y_rad))


def ue_basis_to_rotator(
    f: Tuple[float, float, float],
    r: Tuple[float, float, float],
    u: Tuple[float, float, float],
) -> Tuple[float, float, float]:
    """
    Extracts an Unreal Rotator (Pitch, Yaw, Roll in degrees) from an Unreal
    orthonormal frame (forward / right / up), matching Unreal's FRotationMatrix:
      forward = (CP*CY, CP*SY, SP)
      right   = (SR*SP*CY - CR*SY, SR*SP*SY + CR*CY, -SR*CP)
      up      = (-(CR*SP*CY + SR*SY), CY*SR - CR*SP*SY, CR*CP)
    so roll follows from atan2(-right.z, up.z).
    """
    yaw_deg = math.degrees(math.atan2(f[1], f[0]))
    horiz_dist = math.sqrt(f[0] * f[0] + f[1] * f[1])
    pitch_deg = math.degrees(math.atan2(f[2], horiz_dist))
    roll_deg = math.degrees(math.atan2(-r[2], u[2]))
    return (pitch_deg, yaw_deg, roll_deg)


def _quat_from_euler_xyz(x: float, y: float, z: float) -> Dict[str, float]:
    """Three.js Quaternion.setFromEuler with the default 'XYZ' order (radians)."""
    c1, c2, c3 = math.cos(x / 2), math.cos(y / 2), math.cos(z / 2)
    s1, s2, s3 = math.sin(x / 2), math.sin(y / 2), math.sin(z / 2)
    return {
        'x': s1 * c2 * c3 + c1 * s2 * s3,
        'y': c1 * s2 * c3 - s1 * c2 * s3,
        'z': c1 * c2 * s3 + s1 * s2 * c3,
        'w': c1 * c2 * c3 - s1 * s2 * s3,
    }


def _quat_mul(a: Dict[str, float], b: Dict[str, float]) -> Dict[str, float]:
    """Hamilton product a*b, i.e. apply b first then a (parent * child)."""
    return {
        'x': a['w'] * b['x'] + a['x'] * b['w'] + a['y'] * b['z'] - a['z'] * b['y'],
        'y': a['w'] * b['y'] - a['x'] * b['z'] + a['y'] * b['w'] + a['z'] * b['x'],
        'z': a['w'] * b['z'] + a['x'] * b['y'] - a['y'] * b['x'] + a['z'] * b['w'],
        'w': a['w'] * b['w'] - a['x'] * b['x'] - a['y'] * b['y'] - a['z'] * b['z'],
    }


def _quat_rotate(q: Dict[str, float], v: Tuple[float, float, float]) -> Tuple[float, float, float]:
    """Rotates a vector by a quaternion (v' = q v q*)."""
    x, y, z, w = q['x'], q['y'], q['z'], q['w']
    tx = 2.0 * (y * v[2] - z * v[1])
    ty = 2.0 * (z * v[0] - x * v[2])
    tz = 2.0 * (x * v[1] - y * v[0])
    return (
        v[0] + w * tx + (y * tz - z * ty),
        v[1] + w * ty + (z * tx - x * tz),
        v[2] + w * tz + (x * ty - y * tx),
    )


def sv_actor_rotator(rotation_y_rad: float, stance: str) -> Tuple[float, float, float]:
    """
    Full Unreal Rotator for an actor, combining heading with the stance body Euler.

    SetView builds the actor as `root.rotation.y = rotationY` with a child
    `body.rotation.set(bodyRot)` (src/actors.ts), so the world rotation is
    R_y(heading) * R_xyz(bodyRot). Actors face local +Z (rotationY 0 = +Z), unlike
    cameras which look down -Z -- do not route actors through sv_quat_to_ue_rotator.

    The whole basis is mapped and re-extracted rather than assembling
    (stance_pitch, heading_yaw, stance_roll) component-wise. That shortcut is only
    valid when the three commute; with a 90-degree stance pitch (any of the lying
    poses) yaw and roll gimbal-couple and the actor lands in the wrong orientation.
    """
    info = STANCES.get(stance, STANCES['standing'])
    bx, by, bz = info['bodyRot']
    q = _quat_mul(_quat_from_euler_xyz(0.0, rotation_y_rad, 0.0), _quat_from_euler_xyz(bx, by, bz))

    forward = sv_direction_to_ue(_quat_rotate(q, (0.0, 0.0, 1.0)))
    right = sv_direction_to_ue(_quat_rotate(q, (1.0, 0.0, 0.0)))
    up = sv_direction_to_ue(_quat_rotate(q, (0.0, 1.0, 0.0)))
    return ue_basis_to_rotator(forward, right, up)


def sv_quat_to_ue_rotator(q: Dict[str, float]) -> Tuple[float, float, float]:
    """
    Converts Three.js / SetView camera quaternion to Unreal Engine Rotator (Pitch, Yaw, Roll in degrees).
    Three.js camera default forward is (0, 0, -1), up is (0, 1, 0), right is (1, 0, 0).
    An identity quaternion yields (0, 0, 0): the Unreal camera faces +X.
    """
    qx = float(q.get('x', 0.0))
    qy = float(q.get('y', 0.0))
    qz = float(q.get('z', 0.0))
    qw = float(q.get('w', 1.0))

    q_len = math.sqrt(qx * qx + qy * qy + qz * qz + qw * qw)
    if q_len > 1e-9:
        qx, qy, qz, qw = qx / q_len, qy / q_len, qz / q_len, qw / q_len
    else:
        qx, qy, qz, qw = 0.0, 0.0, 0.0, 1.0

    # Forward vector in Three.js camera space: R * (0, 0, -1)
    f_sv = (
        -2.0 * (qx * qz + qw * qy),
        -2.0 * (qy * qz - qw * qx),
        -(1.0 - 2.0 * (qx * qx + qy * qy)),
    )
    # Up vector in Three.js camera space: R * (0, 1, 0)
    u_sv = (
        2.0 * (qx * qy - qw * qz),
        1.0 - 2.0 * (qx * qx + qz * qz),
        2.0 * (qy * qz + qw * qx),
    )
    # Right vector in Three.js camera space: R * (1, 0, 0)
    r_sv = (
        1.0 - 2.0 * (qy * qy + qz * qz),
        2.0 * (qx * qy + qw * qz),
        2.0 * (qx * qz - qw * qy),
    )

    return ue_basis_to_rotator(
        sv_direction_to_ue(f_sv),
        sv_direction_to_ue(r_sv),
        sv_direction_to_ue(u_sv),
    )


def hex_to_rgb(hex_str: str) -> Tuple[float, float, float]:
    """Converts hex color string (#rrggbb) to linear RGB tuple (0.0 - 1.0)."""
    hex_str = hex_str.lstrip('#')
    if len(hex_str) == 6:
        r = int(hex_str[0:2], 16) / 255.0
        g = int(hex_str[2:4], 16) / 255.0
        b = int(hex_str[4:6], 16) / 255.0
        return (r, g, b)
    return (1.0, 1.0, 1.0)


def sanitize_asset_name(name: str, fallback: str = 'SetViewScene') -> str:
    """Unreal object paths reject spaces and most punctuation in asset names."""
    cleaned = ''.join(ch if ch.isalnum() else '_' for ch in str(name).strip())
    while '__' in cleaned:
        cleaned = cleaned.replace('__', '_')
    return cleaned.strip('_') or fallback


def unwrap_deg(prev: float, cur: float) -> float:
    """Nearest equivalent angle so linear yaw keys take the shortest arc."""
    while cur - prev > 180.0:
        cur -= 360.0
    while cur - prev < -180.0:
        cur += 360.0
    return cur


def ue_up_vector(pitch_deg: float, yaw_deg: float, roll_deg: float) -> Tuple[float, float, float]:
    """Up row of Unreal's FRotationMatrix for a rotator (see ue_basis_to_rotator)."""
    sp, cp = math.sin(math.radians(pitch_deg)), math.cos(math.radians(pitch_deg))
    sy, cy = math.sin(math.radians(yaw_deg)), math.cos(math.radians(yaw_deg))
    sr, cr = math.sin(math.radians(roll_deg)), math.cos(math.radians(roll_deg))
    return (-(cr * sp * cy + sr * sy), cy * sr - cr * sp * sy, cr * cp)


def actor_placeholder_transform(
    position: Dict[str, float],
    rotation_y_rad: float,
    stance: str,
    height_m: float = ACTOR_HEIGHT_M_DEFAULT,
) -> Tuple[Tuple[float, float, float], Tuple[float, float, float]]:
    """
    Feet-origin SetView mark -> center-pivot placeholder cylinder (loc cm, rotator deg).

    The engine cylinder's pivot is its center, so the center sits half the body
    height along the body's LOCAL up axis from the feet: upright stances rise
    +Z by half the height, lying stances shift horizontally so the feet stay
    on the mark. bodyLift (seated stances) applies along world up.
    """
    info = STANCES.get(stance, STANCES['standing'])
    rot = sv_actor_rotator(rotation_y_rad, stance)
    up = ue_up_vector(*rot)
    half_cm = float(height_m) * SCALE_M_TO_CM / 2.0
    base = sv_to_ue_location(position)
    lift_cm = info['bodyLift'] * SCALE_M_TO_CM
    loc = (
        base[0] + up[0] * half_cm,
        base[1] + up[1] * half_cm,
        base[2] + lift_cm + up[2] * half_cm,
    )
    return loc, rot


# --- Binary Scan Mesh Decoder ------------------------------------------------

def decode_scan_data(b64_data: str) -> Optional[List[Dict[str, Any]]]:
    """
    Decodes embedded base64 scan binary data format:
      u32 version (1)
      f64 capturedAt
      u32 mesh_count
      per mesh:
        u32 label_len + UTF-8 bytes
        u32 pos_count (3 * verts)
        u8 index_width (2 | 4)
        u32 idx_count (3 * tris)
        f32... positions, u16|u32... indices
    """
    try:
        raw = base64.b64decode(b64_data)
        if len(raw) < 16:
            return None

        o = 0
        version, = struct.unpack_from('<I', raw, o); o += 4
        if version != 1:
            return None

        captured_at, = struct.unpack_from('<d', raw, o); o += 8
        mesh_count, = struct.unpack_from('<I', raw, o); o += 4

        meshes = []
        for _ in range(mesh_count):
            label_len, = struct.unpack_from('<I', raw, o); o += 4
            label_bytes = raw[o:o + label_len]; o += label_len
            label = label_bytes.decode('utf-8', errors='ignore')

            pos_count, = struct.unpack_from('<I', raw, o); o += 4
            idx_width = raw[o]; o += 1
            idx_count, = struct.unpack_from('<I', raw, o); o += 4

            positions = list(struct.unpack_from(f'<{pos_count}f', raw, o))
            o += pos_count * 4

            if idx_width == 4:
                indices = list(struct.unpack_from(f'<{idx_count}I', raw, o))
                o += idx_count * 4
            else:
                indices = list(struct.unpack_from(f'<{idx_count}H', raw, o))
                o += idx_count * 2

            meshes.append({
                'label': label,
                'positions': positions,
                'indices': indices
            })

        return meshes
    except Exception as e:
        print(f"[SetView] Warning: Failed to decode scan binary data: {e}")
        return None


def export_scan_to_obj(meshes: List[Dict[str, Any]], obj_path: str) -> bool:
    """Writes decoded scan meshes to Wavefront OBJ format on disk."""
    try:
        os.makedirs(os.path.dirname(os.path.abspath(obj_path)), exist_ok=True)
        with open(obj_path, 'w', encoding='utf-8') as f:
            f.write("# SetView Location Scan Export\n")
            # One dummy UV shared by every face corner: Unreal's Interchange OBJ
            # translator fires a per-corner "UVs.IsValidIndex" ensure on faces
            # that reference no texture coordinate at all.
            f.write("vt 0.0 0.0\n")
            v_offset = 1
            for m_idx, mesh in enumerate(meshes):
                f.write(f"o ScanMesh_{m_idx}_{mesh['label'].replace(' ', '_')}\n")
                positions = mesh['positions']
                indices = mesh['indices']

                for i in range(0, len(positions), 3):
                    # Single shared handedness contract: SV meters -> UE cm (det -1).
                    x_ue, y_ue, z_ue = sv_to_ue_location({
                        'x': positions[i],
                        'y': positions[i+1],
                        'z': positions[i+2],
                    })
                    f.write(f"v {x_ue:.4f} {y_ue:.4f} {z_ue:.4f}\n")

                for i in range(0, len(indices), 3):
                    i0 = indices[i] + v_offset
                    i1 = indices[i+1] + v_offset
                    i2 = indices[i+2] + v_offset
                    # The det -1 vertex map flips triangle handedness, so the winding
                    # must be reversed or every imported scan face renders inside-out.
                    f.write(f"f {i0}/1 {i2}/1 {i1}/1\n")

                v_offset += len(positions) // 3
        return True
    except Exception as e:
        print(f"[SetView] Error writing OBJ file: {e}")
        return False


# --- Unreal Engine Importer Logic --------------------------------------------

def import_scene_to_unreal(scene_data: Dict[str, Any], verbose: bool = True) -> bool:
    """
    Main importer routine executing inside Unreal Engine environment.
    Creates CineCameraActors, MetaHuman/Placeholder Actors, LevelSequence, Cine Lights, Scan Meshes.
    """
    if not IN_UNREAL:
        print("[SetView] Error: Not inside Unreal Engine environment (unreal module not available).")
        return False

    scene_name = scene_data.get('name', 'SetViewScene').strip()
    walk_speed = float(scene_data.get('walkSpeed', WALK_SPEED_DEFAULT))
    actors_data = scene_data.get('actors', [])
    cameras_data = scene_data.get('cameras', [])
    lights_data = scene_data.get('lights', [])
    scan_summary = scene_data.get('scan')
    scan_b64 = scene_data.get('scanData')

    print(f"[SetView] Starting import for '{scene_name}' (walk speed: {walk_speed} m/s)...")

    # 1. Editor World / Subsystem Setup
    editor_actor_subsystem = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    level_subsystem = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

    # Asset names reject spaces and most punctuation; scene names are free text.
    safe_name = sanitize_asset_name(scene_name)
    package_path = f"/Game/SetView/{safe_name}"
    outliner_folder = f"SetView/{safe_name}"

    # A dedicated level per scene: an in-editor import never dirties the map
    # the user has open, and a headless import has a real asset to save.
    level_path = f"{package_path}/Maps/SV_{safe_name}"
    if unreal.EditorAssetLibrary.does_asset_exist(level_path):
        level_subsystem.load_level(level_path)
    else:
        if not level_subsystem.new_level(level_path):
            print(f"[SetView] Error: could not create level {level_path}")
            return False

    # 2. Import Location Scan Static Mesh (if present)
    scan_actor = None
    if scan_b64:
        meshes = decode_scan_data(scan_b64)
        if meshes:
            temp_dir = unreal.Paths.project_saved_dir() + "SetViewTemp/"
            obj_file = temp_dir + f"{safe_name}_scan.obj"
            if export_scan_to_obj(meshes, obj_file):
                print(f"[SetView] Exported scan OBJ to {obj_file}, importing into Unreal...")
                scan_asset_name = f"SM_{safe_name}_Scan"
                task = unreal.AssetImportTask()
                task.filename = obj_file
                task.destination_path = package_path + "/Scans"
                task.destination_name = scan_asset_name
                task.automated = True
                task.replace_existing = True
                task.save = True
                asset_tools.import_asset_tasks([task])

                imported_mesh = unreal.EditorAssetLibrary.load_asset(f"{package_path}/Scans/{scan_asset_name}")
                if imported_mesh:
                    scan_actor = editor_actor_subsystem.spawn_actor_from_class(
                        unreal.StaticMeshActor, unreal.Vector(0, 0, 0), unreal.Rotator()
                    )
                    scan_actor.set_actor_label(f"Scan_{safe_name}")
                    scan_actor.set_folder_path(outliner_folder)
                    scan_actor.static_mesh_component.set_static_mesh(imported_mesh)
                    print("[SetView] Spawned location scan static mesh actor.")

    # 3. Create CineCameraActors
    spawned_cameras: Dict[str, Any] = {}
    for c_data in cameras_data:
        cam_name = c_data.get('name', 'CAM')
        pos_ue = sv_to_ue_location(c_data.get('position', {}))
        rot_ue = sv_quat_to_ue_rotator(c_data.get('rotation', {}))

        # unreal.Rotator's positional order is (roll, pitch, yaw); our tuples are
        # (pitch, yaw, roll) from ue_basis_to_rotator. Always use keywords.
        cam_actor = editor_actor_subsystem.spawn_actor_from_class(
            unreal.CineCameraActor,
            unreal.Vector(*pos_ue),
            unreal.Rotator(roll=rot_ue[2], pitch=rot_ue[0], yaw=rot_ue[1])
        )
        cam_actor.set_actor_label(cam_name)
        cam_actor.set_folder_path(outliner_folder)

        cine_comp = cam_actor.get_cine_camera_component()

        # Set Sensor Format (Filmback)
        fmt_id = c_data.get('formatId', 'super35')
        fmt_info = SENSOR_FORMATS.get(fmt_id, SENSOR_FORMATS['super35'])
        aspect_name = c_data.get('aspect', '16:9')
        aspect_val = ASPECT_RATIOS.get(aspect_name, 16.0 / 9.0)

        gate_width = fmt_info['gateWidthMm']
        gate_height = gate_width / aspect_val

        filmback = cine_comp.filmback
        filmback.sensor_width = gate_width
        filmback.sensor_height = gate_height
        cine_comp.filmback = filmback

        # Set Lens Focal Length & Aperture T-stop
        focal_length = float(c_data.get('lensFocalLength', 35.0))
        t_stop = float(c_data.get('tStop', 2.8))

        cine_comp.current_focal_length = focal_length
        cine_comp.current_aperture = t_stop

        # Focus settings
        focus_settings = cine_comp.focus_settings
        focus_settings.focus_method = unreal.CameraFocusMethod.MANUAL
        focus_settings.manual_focus_distance = 300.0  # 3m default
        cine_comp.focus_settings = focus_settings

        spawned_cameras[c_data['id']] = (cam_actor, cine_comp)
        if verbose:
            print(f"[SetView] Created CineCamera '{cam_name}' ({focal_length}mm, T{t_stop}, {fmt_info['name']})")

    # 4. Create Actors (visible placeholder cylinders, stance-aware)
    cylinder_mesh = unreal.EditorAssetLibrary.load_asset(CYLINDER_ASSET)
    spawned_actors: Dict[str, Any] = {}
    for a_data in actors_data:
        actor_name = a_data.get('name', 'Actor')
        rotation_y = a_data.get('rotationY', 0.0)
        stance = a_data.get('stance', 'standing')
        height_m = float(a_data.get('heightM') or ACTOR_HEIGHT_M_DEFAULT)

        loc, rot = actor_placeholder_transform(
            a_data.get('position', {}), rotation_y, stance, height_m)

        act = editor_actor_subsystem.spawn_actor_from_class(
            unreal.StaticMeshActor,
            unreal.Vector(*loc),
            unreal.Rotator(roll=rot[2], pitch=rot[0], yaw=rot[1])
        )
        act.set_actor_label(actor_name)
        act.set_folder_path(outliner_folder)
        if cylinder_mesh:
            act.static_mesh_component.set_static_mesh(cylinder_mesh)
        # The engine cylinder is 100 cm tall; sequences can only move MOVABLE actors.
        act.set_actor_scale3d(unreal.Vector(
            ACTOR_WIDTH_SCALE, ACTOR_WIDTH_SCALE, height_m * SCALE_M_TO_CM / 100.0))
        act.static_mesh_component.set_mobility(unreal.ComponentMobility.MOVABLE)
        mid = act.static_mesh_component.create_dynamic_material_instance(0)
        if mid:
            r, g, b = hex_to_rgb(a_data.get('color', '#888888'))
            # crude sRGB -> linear for a previz tint
            mid.set_vector_parameter_value(
                'Color', unreal.LinearColor(r ** 2.2, g ** 2.2, b ** 2.2, 1.0))

        spawned_actors[a_data['id']] = (act, a_data)
        if verbose:
            print(f"[SetView] Placed Actor '{actor_name}' at {loc} stance={stance}")

    # 5. Create Cine Light Actors
    for idx, l_data in enumerate(lights_data):
        l_type = l_data.get('type', 'spot').lower()
        l_name = l_data.get('name', f"Light_{idx+1}")
        pos_ue = sv_to_ue_location(l_data.get('position', {}))
        rot_ue = sv_quat_to_ue_rotator(l_data.get('rotation', {})) if 'rotation' in l_data else (0.0, 0.0, 0.0)

        light_class = unreal.SpotLight
        if l_type == 'point':
            light_class = unreal.PointLight
        elif l_type == 'rect':
            light_class = unreal.RectLight

        l_actor = editor_actor_subsystem.spawn_actor_from_class(
            light_class,
            unreal.Vector(*pos_ue),
            unreal.Rotator(roll=rot_ue[2], pitch=rot_ue[0], yaw=rot_ue[1])
        )
        l_actor.set_actor_label(l_name)
        l_actor.set_folder_path(outliner_folder)

        if verbose:
            print(f"[SetView] Created {l_type.capitalize()} Light '{l_name}'")

    # 6. Create Spatial Audio Emitters & Cues
    audio_cues_data = scene_data.get('audioCues', [])
    for idx, cue_data in enumerate(audio_cues_data):
        cue_name = cue_data.get('name', f"AudioCue_{idx+1}")
        cue_type = cue_data.get('type', 'sfx')
        vol = float(cue_data.get('volume', 1.0))
        spatial = bool(cue_data.get('spatial', True))
        max_dist_m = float(cue_data.get('maxDistanceM', 20.0))

        # Position (attached to an actor at head level, or free-standing in the world).
        # Editor Python cannot construct-and-register a bare AudioComponent on an
        # existing actor (it never registers with the world), so attached cues are
        # AmbientSound actors attached to the placeholder with KEEP_WORLD rules.
        attached_act_id = cue_data.get('attachedActorId')
        if attached_act_id and attached_act_id in spawned_actors:
            act_actor, act_data = spawned_actors[attached_act_id]
            base = sv_to_ue_location(act_data.get('position', {}))
            audio_actor = editor_actor_subsystem.spawn_actor_from_class(
                unreal.AmbientSound,
                unreal.Vector(base[0], base[1], base[2] + 150.0),  # head level
                unreal.Rotator()
            )
            audio_actor.set_actor_label(cue_name)
            audio_actor.set_folder_path(outliner_folder)
            audio_actor.attach_to_actor(
                act_actor, '',
                unreal.AttachmentRule.KEEP_WORLD,
                unreal.AttachmentRule.KEEP_WORLD,
                unreal.AttachmentRule.KEEP_WORLD,
                False)
            audio_comp = audio_actor.get_component_by_class(unreal.AudioComponent)
            if audio_comp:
                audio_comp.set_editor_property('volume_multiplier', vol)
            if verbose:
                print(f"[SetView] Attached Audio Cue '{cue_name}' ({cue_type}) to actor '{act_actor.get_actor_label()}'")
        else:
            pos_ue = sv_to_ue_location(cue_data.get('position', {'x':0, 'y':1.5, 'z':0}))
            audio_actor = editor_actor_subsystem.spawn_actor_from_class(
                unreal.AmbientSound,
                unreal.Vector(*pos_ue),
                unreal.Rotator()
            )
            audio_actor.set_actor_label(cue_name)
            audio_actor.set_folder_path(outliner_folder)
            audio_comp = audio_actor.get_component_by_class(unreal.AudioComponent)
            if audio_comp:
                audio_comp.set_editor_property('volume_multiplier', vol)
            if verbose:
                print(f"[SetView] Placed Spatial AmbientSound '{cue_name}' at {pos_ue}")

    # 7. Create LevelSequence Driving Timeline
    def _dist_m(a: Dict[str, float], b: Dict[str, float]) -> float:
        return math.sqrt(
            (float(b.get('x', 0.0)) - float(a.get('x', 0.0))) ** 2
            + (float(b.get('y', 0.0)) - float(a.get('y', 0.0))) ** 2
            + (float(b.get('z', 0.0)) - float(a.get('z', 0.0))) ** 2)

    def _actor_samples(a_data: Dict[str, Any]) -> List[Tuple[float, Tuple, Tuple]]:
        """(time_s, loc_cm, rotator_deg) per keyframe, SetView playback timing:
        distance / walkSpeed with the same minimum segment as src/timeline.ts."""
        keyframes = a_data.get('keyframes', [])
        if len(keyframes) < 2:
            return []
        stance0 = a_data.get('stance', 'standing')
        height_m = float(a_data.get('heightM') or ACTOR_HEIGHT_M_DEFAULT)
        speed = walk_speed if walk_speed > 0 else WALK_SPEED_DEFAULT
        samples: List[Tuple[float, Tuple, Tuple]] = []
        t = 0.0
        prev = None
        for kf in keyframes:
            pos = kf.get('position', a_data.get('position', {}))
            if prev is not None:
                t += max(_dist_m(prev, pos) / speed, MIN_SEGMENT_S)
            loc, rot = actor_placeholder_transform(
                pos, kf.get('rotationY', a_data.get('rotationY', 0.0)),
                kf.get('stance', stance0), height_m)
            samples.append((t, loc, rot))
            hold = float(kf.get('holdDurationS', 0.0))
            if hold > 0.0:
                t += hold
                samples.append((t, loc, rot))
            prev = pos
        return samples

    def _camera_samples(c_data: Dict[str, Any]) -> List[Tuple[float, Tuple, Tuple]]:
        cam_kfs = c_data.get('keyframes', [])
        if len(cam_kfs) < 2:
            return []
        samples: List[Tuple[float, Tuple, Tuple]] = []
        t = 0.0
        prev = None
        for kf in cam_kfs:
            pos = kf.get('position', c_data.get('position', {'x': 0, 'y': 1.6, 'z': 0}))
            if prev is not None:
                t += max(_dist_m(prev, pos) / CAMERA_MOVE_SPEED, MIN_SEGMENT_S)
            rot = sv_quat_to_ue_rotator(kf.get('rotation', c_data.get('rotation', {})))
            samples.append((t, sv_to_ue_location(pos), rot))
            hold = float(kf.get('holdDurationS', 0.0))
            if hold > 0.0:
                t += hold
                samples.append((t, sv_to_ue_location(pos), rot))
            prev = pos
        return samples

    def _write_transform_keys(section: Any, samples: List[Tuple[float, Tuple, Tuple]]) -> int:
        """Channel order on a 3D transform section: Loc XYZ 0-2,
        Rot XYZ = (roll, pitch, yaw) 3-5, Scale XYZ 6-8."""
        channels = section.get_all_channels()
        linear = unreal.MovieSceneKeyInterpolation.LINEAR
        keys = 0
        prev_yaw = None
        for t, loc, rot in samples:
            frame = unreal.FrameNumber(round(t * SEQUENCE_FPS))
            channels[0].add_key(frame, loc[0], interpolation=linear)
            channels[1].add_key(frame, loc[1], interpolation=linear)
            channels[2].add_key(frame, loc[2], interpolation=linear)
            keys += 3
            if rot is not None:
                pitch, yaw, roll = rot
                if prev_yaw is not None:
                    yaw = unwrap_deg(prev_yaw, yaw)
                prev_yaw = yaw
                channels[3].add_key(frame, roll, interpolation=linear)
                channels[4].add_key(frame, pitch, interpolation=linear)
                channels[5].add_key(frame, yaw, interpolation=linear)
                keys += 3
        return keys

    seq_name = f"LS_{safe_name}"
    seq_path = f"{package_path}/Sequences/{seq_name}"
    # The sequence is generated data derived from the JSON: a re-import replaces
    # it wholesale instead of appending duplicate bindings to the old asset.
    if unreal.EditorAssetLibrary.does_asset_exist(seq_path):
        unreal.EditorAssetLibrary.delete_asset(seq_path)
    sequence = asset_tools.create_asset(
        seq_name, package_path + "/Sequences", unreal.LevelSequence, unreal.LevelSequenceFactoryNew()
    )

    sequence_key_counts: Dict[str, int] = {}
    end_frame = 0
    if sequence:
        sequence.set_display_rate(unreal.FrameRate(SEQUENCE_FPS, 1))

        binding_plan: List[Tuple[str, Any, List]] = []
        for cam_id, (cam_actor, _cine_comp) in spawned_cameras.items():
            c_data = next((c for c in cameras_data if c.get('id') == cam_id), None)
            binding_plan.append((
                cam_actor.get_actor_label(), cam_actor,
                _camera_samples(c_data) if c_data else []))
        for _act_id, (act_actor, a_data) in spawned_actors.items():
            binding_plan.append((act_actor.get_actor_label(), act_actor, _actor_samples(a_data)))

        end_seconds = max((s[-1][0] for _, _, s in binding_plan if s), default=0.0)
        end_frame = max(int(round(end_seconds * SEQUENCE_FPS)), SEQUENCE_FPS)
        sequence.set_playback_start(0)
        sequence.set_playback_end(end_frame + 1)

        first_cam_binding = None
        for label, actor, samples in binding_plan:
            possessable = sequence.add_possessable(actor)
            if first_cam_binding is None and isinstance(actor, unreal.CineCameraActor):
                first_cam_binding = possessable
            if not samples:
                sequence_key_counts[label] = 0
                continue
            track = possessable.add_track(unreal.MovieScene3DTransformTrack)
            section = track.add_section()
            section.set_range(0, end_frame + 1)
            sequence_key_counts[label] = _write_transform_keys(section, samples)

        # Camera cut: bind the full range to the hero (first) camera so opening
        # the sequence looks through it. Per-cut data would come from the dailies
        # timeline, which the scene JSON does not carry today.
        if first_cam_binding is not None:
            cut_track = sequence.add_track(unreal.MovieSceneCameraCutTrack)
            cut_section = cut_track.add_section()
            cut_section.set_range(0, end_frame + 1)
            if hasattr(sequence, 'make_binding_id'):
                binding_id = sequence.make_binding_id(
                    first_cam_binding, unreal.MovieSceneObjectBindingSpace.LOCAL)
            else:
                binding_id = sequence.get_binding_id(first_cam_binding)
            cut_section.set_camera_binding_id(binding_id)

        unreal.EditorAssetLibrary.save_loaded_asset(sequence)
        print(f"[SetView] Created LevelSequence '{seq_name}' ({end_frame} frames @ {SEQUENCE_FPS}fps).")

    # 8. Persist the level and write ground truth for headless verification
    level_subsystem.save_current_level()

    spawned_report = []
    for _sid, (sp_actor, _d) in list(spawned_cameras.items()) + list(spawned_actors.items()):
        loc = sp_actor.get_actor_location()
        rot = sp_actor.get_actor_rotation()
        spawned_report.append({
            'label': str(sp_actor.get_actor_label()),
            'class': sp_actor.get_class().get_name(),
            'loc': [loc.x, loc.y, loc.z],
            'rot': {'pitch': rot.pitch, 'yaw': rot.yaw, 'roll': rot.roll},
        })

    report = {
        'scene': scene_name,
        'safeName': safe_name,
        'levelPath': level_path,
        'sequencePath': seq_path if sequence else None,
        'endFrame': end_frame,
        'counts': {
            'cameras': len(spawned_cameras),
            'actors': len(spawned_actors),
            'lights': len(lights_data),
            'audioCues': len(audio_cues_data),
            'scanImported': scan_actor is not None,
        },
        'sequenceKeyCounts': sequence_key_counts,
        'spawned': spawned_report,
    }
    report_path = os.path.join(unreal.Paths.project_saved_dir(), 'SetViewTemp', 'import_report.json')
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2)

    # log_warning so the summary surfaces in -stdout headless runs, where
    # Display-severity Python prints are filtered out.
    unreal.log_warning(
        f"[SetView] Imported '{scene_name}': {len(spawned_actors)} actors, "
        f"{len(spawned_cameras)} cameras, {len(lights_data)} lights, "
        f"level {level_path}, report {report_path}")
    print(f"[SetView] Import complete for '{scene_name}'!")
    return True


# --- CLI Verification & Diagnostics ------------------------------------------

def verify_scene_json(file_path: str, verbose: bool = True) -> bool:
    """
    Parses and verifies a .setview.json file, testing all transform calculations
    and reporting scene components without requiring Unreal Engine.
    """
    if not os.path.exists(file_path):
        print(f"[SetView Error] File not found: {file_path}")
        return False

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"[SetView Error] Failed to parse JSON file '{file_path}': {e}")
        return False

    # Validation checks
    version = data.get('version')
    if version != 1:
        print(f"[SetView Warning] Expected version 1, got {version}")

    scene_name = data.get('name', 'Unnamed Scene')
    walk_speed = data.get('walkSpeed', WALK_SPEED_DEFAULT)
    actors = data.get('actors', [])
    cameras = data.get('cameras', [])
    lights = data.get('lights', [])
    scan_summary = data.get('scan')
    scan_b64 = data.get('scanData')

    print("=" * 70)
    print(f"SetView Scene JSON Verification Summary: {scene_name}")
    print("=" * 70)
    print(f"  - Version: {version}")
    print(f"  - Walk Speed: {walk_speed} m/s")
    print(f"  - Cameras Count: {len(cameras)}")
    print(f"  - Actors Count: {len(actors)}")
    print(f"  - Lights Count: {len(lights)}")
    print(f"  - Scan Summary Present: {scan_summary is not None}")
    print(f"  - Embedded Scan Binary Data Present: {scan_b64 is not None}")
    print("-" * 70)

    # Test Camera conversions
    for idx, c in enumerate(cameras):
        cam_name = c.get('name', f"CAM_{idx+1}")
        fmt_id = c.get('formatId', 'super35')
        fmt = SENSOR_FORMATS.get(fmt_id, SENSOR_FORMATS['super35'])
        focal = c.get('lensFocalLength', 35.0)
        tstop = c.get('tStop', 2.8)
        aspect = c.get('aspect', '16:9')

        pos_ue = sv_to_ue_location(c.get('position', {}))
        rot_ue = sv_quat_to_ue_rotator(c.get('rotation', {}))

        cam_kfs = c.get('keyframes', [])
        look_target = c.get('lookAtTargetActorId')

        if verbose:
            print(f"[Camera {cam_name}]")
            print(f"  Sensor: {fmt['name']} ({fmt['gateWidthMm']}mm gate, {aspect})")
            print(f"  Optics: {focal}mm, T{tstop}")
            print(f"  Unreal Location (cm): ({pos_ue[0]:.2f}, {pos_ue[1]:.2f}, {pos_ue[2]:.2f})")
            print(f"  Unreal Rotator (deg): Pitch={rot_ue[0]:.2f}, Yaw={rot_ue[1]:.2f}, Roll={rot_ue[2]:.2f}")
            if cam_kfs:
                print(f"  Motion Path Marks: {len(cam_kfs)} keyframes")
            if look_target:
                print(f"  Look-At Target Actor ID: {look_target}")

    # Test Actor conversions
    for idx, a in enumerate(actors):
        act_name = a.get('name', f"Actor_{idx+1}")
        stance = a.get('stance', 'standing')
        pos_ue = sv_to_ue_location(a.get('position', {}))
        rot_ue = sv_actor_rotator(a.get('rotationY', 0.0), stance)
        kfs = a.get('keyframes', [])

        if verbose:
            print(f"[Actor {act_name}]")
            print(f"  Stance: {stance}")
            print(f"  Unreal Location (cm): ({pos_ue[0]:.2f}, {pos_ue[1]:.2f}, {pos_ue[2]:.2f})")
            print(f"  Unreal Rotator (deg): Pitch={rot_ue[0]:.2f}, Yaw={rot_ue[1]:.2f}, Roll={rot_ue[2]:.2f}")
            print(f"  Keyframe Marks: {len(kfs)}")

            total_dist_m = 0.0
            last_p = a.get('position', {'x':0,'y':0,'z':0})
            for k_idx, kf in enumerate(kfs):
                kp = kf.get('position', last_p)
                dx, dy, dz = kp['x'] - last_p['x'], kp['y'] - last_p['y'], kp['z'] - last_p['z']
                dist_m = math.sqrt(dx*dx + dy*dy + dz*dz)
                total_dist_m += dist_m
                last_p = kp
            dur_sec = total_dist_m / walk_speed if walk_speed > 0 else 0.0
            print(f"  Total Walk Distance: {total_dist_m:.2f}m (~{dur_sec:.2f}s at {walk_speed}m/s)")

    # Test Audio Cues
    audio_cues = data.get('audioCues', [])
    if audio_cues:
        print(f"[Spatial Audio Cues] {len(audio_cues)} cues defined:")
        for idx, cue in enumerate(audio_cues):
            c_name = cue.get('name', f"Cue_{idx+1}")
            c_type = cue.get('type', 'sfx')
            t_s = float(cue.get('timestampS', 0.0))
            d_s = float(cue.get('durationS', 1.0))
            vol = float(cue.get('volume', 1.0))
            spat = bool(cue.get('spatial', True))
            att_act = cue.get('attachedActorId')

            att_info = f"attached to actor {att_act}" if att_act else "static world emitter"
            print(f"  - [{c_type.upper()}] '{c_name}' @ {t_s:.2f}s ({d_s:.2f}s) Vol={vol:.2f} Spatial={spat} ({att_info})")

    # Multi-Camera Continuity Audit (180 line & 30-degree jump cuts)
    if len(cameras) >= 2 and len(actors) >= 2:
        a1_pos = actors[0].get('position', {'x': 0, 'z': 0})
        a2_pos = actors[1].get('position', {'x': 0, 'z': 0})
        line_dx = a2_pos.get('x', 0) - a1_pos.get('x', 0)
        line_dz = a2_pos.get('z', 0) - a1_pos.get('z', 0)

        sides = []
        for c in cameras:
            c_pos = c.get('position', {'x': 0, 'z': 0})
            cross = line_dx * (c_pos.get('z', 0) - a1_pos.get('z', 0)) - line_dz * (c_pos.get('x', 0) - a1_pos.get('x', 0))
            sides.append(1 if cross > 0.05 else (-1 if cross < -0.05 else 0))

        has_180_crossing = (1 in sides) and (-1 in sides)
        status_str = "WARNING (Cameras cross interaction axis)" if has_180_crossing else "CLEAN (All cameras on same side)"
        print(f"[Continuity Audit] 180-Degree Line Status: {status_str}")

    # Test Scan decoding if binary data present
    if scan_b64:
        meshes = decode_scan_data(scan_b64)
        if meshes:
            total_verts = sum(len(m['positions']) // 3 for m in meshes)
            total_tris = sum(len(m['indices']) // 3 for m in meshes)
            print(f"[Location Scan] Decoded {len(meshes)} meshes, {total_verts} vertices, {total_tris} triangles.")
        else:
            print("[Location Scan] Warning: scanData binary blob could not be decoded.")

    print("=" * 70)
    print("Verification completed successfully — JSON is valid for SetView Unreal Handoff.")
    print("=" * 70)
    return True


def import_scene_to_unreal_from_file(json_path: str, verbose: bool = True) -> bool:
    """File-path entry point documented in UNREAL-HANDOFF.md."""
    with open(json_path, 'r', encoding='utf-8') as f:
        scene_data = json.load(f)
    return import_scene_to_unreal(scene_data, verbose=verbose)


def import_scene(json_path: str, verbose: bool = True) -> bool:
    """Backward-compatible entry point documented in SETVIEW_IMPORT.md."""
    return import_scene_to_unreal_from_file(json_path, verbose=verbose)


def main():
    parser = argparse.ArgumentParser(description="SetView -> Unreal Engine 5.8 Scene Importer")
    parser.add_argument("json_path", nargs="?", help="Path to .setview.json file")
    parser.add_argument("--verbose", "-v", action="store_true", help="Print detailed transformation readouts")
    args = parser.parse_args()

    if not args.json_path:
        print("Usage: python3 import_setview.py /path/to/scene.setview.json")
        sys.exit(1)

    success = verify_scene_json(args.json_path, verbose=args.verbose)

    if IN_UNREAL and success:
        with open(args.json_path, 'r', encoding='utf-8') as f:
            scene_data = json.load(f)
        import_scene_to_unreal(scene_data, verbose=args.verbose)

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
