// ---------------------------------------------------------------------------
// SetView Pure Domain Virtual Set Dressing, Generative Scatter & Gemini AI Engine
// PURE DOMAIN MODULE - ZERO Three.js or DOM imports.
// Suitable for direct execution in Node.js unit tests and headless runtimes.
// ---------------------------------------------------------------------------

import type { PropData, SceneData, Vec3 } from './model.ts';

/** Supported generative dressing thematic archetypes. */
export type ScatterTheme =
  | 'film_noir_office'
  | 'sci_fi_corridor'
  | 'victorian_parlor'
  | 'modern_soundstage'
  | 'cyberpunk_alley'
  | 'custom';

/** Spatial surface target classifications for prop scattering. */
export type ScatterSurfaceType = 'floor' | 'wall' | 'tabletop' | 'perimeter';

/** Density distribution presets for procedural scattering. */
export type ScatterDensity = 'sparse' | 'medium' | 'dense';

/** 3D Axis-Aligned Bounding Box. */
export interface BoundingBox3D {
  min: Vec3;
  max: Vec3;
}

/** Detected or user-defined semantic scatter region in scene space. */
export interface ScatterRegion {
  id: string;
  name: string;
  type: ScatterSurfaceType;
  bounds: BoundingBox3D;
  anchorEntityId?: string;
}

/** Curated 3D prop template definition for generative scattering. */
export interface ScatterItemTemplate {
  name: string;
  propType: string;
  defaultScale: Vec3;
  colorOptions: string[];
  collisionRadius: number;
  heightM: number;
  placementSurface: 'floor' | 'tabletop' | 'wall';
  stackable: boolean;
  maxStackCount: number;
  weightKg: number;
}

/** Settled procedural prop instance placed in scene space. */
export interface SettledPropItem {
  id: string;
  templateName: string;
  propType: string;
  name: string;
  position: Vec3;
  rotation: Vec3;
  scale: Vec3;
  color: string;
  isSettled: boolean;
  stackLevel: number;
  surfaceY: number;
  weightKg: number;
}

/** Generative spatial scatter generator configuration. */
export interface GenerativeScatterConfig {
  theme: ScatterTheme;
  density: ScatterDensity;
  minDistanceM: number;
  seed: number;
  alignToWalls: boolean;
  enablePhysicsSettling: boolean;
  groundY: number;
  maxItems: number;
  customPrompt?: string;
}

/** Structured scene mutation generated by Gemini AI or offline NLP. */
export interface GeminiAiSceneMutation {
  action:
    | 'add_prop'
    | 'update_prop'
    | 'remove_prop'
    | 'modify_lighting'
    | 'modify_atmosphere'
    | 'scatter_theme'
    | 'batch_mutate';
  parameters: Record<string, any>;
  explanation: string;
}

/** Gemini AI Omni Set Director configuration and model settings. */
export interface GeminiAiConfig {
  apiKey?: string;
  model: 'gemini-2.5-flash' | 'gemini-2.5-pro' | 'gemini-2.0-flash-lite';
  systemInstruction?: string;
  temperature: number;
}

/** Complete set dressing state attached to SceneData. */
export interface SetDressingConfig {
  enabled: boolean;
  activeTheme: ScatterTheme;
  scatterConfig: GenerativeScatterConfig;
  aiConfig: GeminiAiConfig;
  regions: ScatterRegion[];
  settledItems: SettledPropItem[];
}

/** Comprehensive set dressing manifest for procurement and exports. */
export interface SetDressingManifest {
  sceneId?: string;
  sceneName?: string;
  theme: ScatterTheme;
  totalItems?: number;
  totalItemCount?: number;
  items: SettledPropItem[];
  boundingVolumeM3?: number;
  totalWeightKg?: number;
  generatedAt: string;
}



// ---------------------------------------------------------------------------
// Curated Theme Prop Catalogs
// ---------------------------------------------------------------------------

export const THEME_PROP_CATALOGS: Record<ScatterTheme, ScatterItemTemplate[]> = {
  film_noir_office: [
    {
      name: 'Vintage Desk Phone',
      propType: 'phone_vintage',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#1a1a1a', '#2a2a2a', '#382d24'],
      collisionRadius: 0.12,
      heightM: 0.18,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 2.5,
    },
    {
      name: 'Desk Lamp Banker',
      propType: 'lamp_banker',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#2d5a27', '#d4af37', '#1b3817'],
      collisionRadius: 0.15,
      heightM: 0.35,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 3.2,
    },
    {
      name: 'Whiskey Decanter & Glass',
      propType: 'whiskey_set',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#d97706', '#b45309', '#f59e0b'],
      collisionRadius: 0.1,
      heightM: 0.22,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 1.8,
    },
    {
      name: 'Case Files & Manila Folders',
      propType: 'case_folders',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#d4b886', '#c2a675', '#a38453'],
      collisionRadius: 0.16,
      heightM: 0.04,
      placementSurface: 'tabletop',
      stackable: true,
      maxStackCount: 5,
      weightKg: 0.8,
    },
    {
      name: 'Glass Ashtray with Cigar',
      propType: 'ashtray',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#475569', '#334155', '#64748b'],
      collisionRadius: 0.08,
      heightM: 0.05,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 0.6,
    },
    {
      name: 'Typewriter Underwood',
      propType: 'typewriter',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#1e293b', '#0f172a', '#334155'],
      collisionRadius: 0.22,
      heightM: 0.2,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 9.5,
    },
    {
      name: 'Leather Armchair',
      propType: 'leather_chair',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#582f0e', '#3f1d0b', '#7f4f24'],
      collisionRadius: 0.45,
      heightM: 0.9,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 22.0,
    },
    {
      name: 'Filing Cabinet 4-Drawer',
      propType: 'filing_cabinet',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#334155', '#475569', '#1e293b'],
      collisionRadius: 0.35,
      heightM: 1.35,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 38.0,
    },
    {
      name: 'Venetian Blinds Shadow Caster',
      propType: 'venetian_blinds',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#94a3b8', '#cbd5e1'],
      collisionRadius: 0.25,
      heightM: 1.8,
      placementSurface: 'wall',
      stackable: false,
      maxStackCount: 1,
      weightKg: 4.0,
    },
    {
      name: 'Floor Coat Rack with Fedora',
      propType: 'coat_rack',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#451a03', '#291508'],
      collisionRadius: 0.25,
      heightM: 1.85,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 8.5,
    },
  ],

  sci_fi_corridor: [
    {
      name: 'Energy Conduit Core',
      propType: 'energy_conduit',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#06b6d4', '#0284c7', '#3b82f6'],
      collisionRadius: 0.28,
      heightM: 1.2,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 45.0,
    },
    {
      name: 'Server Holo Terminal',
      propType: 'holo_terminal',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#1e293b', '#0f172a', '#38bdf8'],
      collisionRadius: 0.3,
      heightM: 0.95,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 24.0,
    },
    {
      name: 'Modular Hex Storage Crate',
      propType: 'hex_crate',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#e2e8f0', '#94a3b8', '#64748b'],
      collisionRadius: 0.28,
      heightM: 0.35,
      placementSurface: 'floor',
      stackable: true,
      maxStackCount: 4,
      weightKg: 14.0,
    },
    {
      name: 'Data Pad Diagnostic Deck',
      propType: 'datapad',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#0f172a', '#0284c7', '#38bdf8'],
      collisionRadius: 0.12,
      heightM: 0.02,
      placementSurface: 'tabletop',
      stackable: true,
      maxStackCount: 3,
      weightKg: 0.5,
    },
    {
      name: 'Cryo Stasis Canister',
      propType: 'cryo_canister',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#0284c7', '#06b6d4', '#0891b2'],
      collisionRadius: 0.35,
      heightM: 1.6,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 65.0,
    },
    {
      name: 'Hydraulic Floor Vent Grate',
      propType: 'floor_vent',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#334155', '#1e293b'],
      collisionRadius: 0.4,
      heightM: 0.05,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 18.0,
    },
    {
      name: 'Wall Interface Screen',
      propType: 'wall_interface',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#0284c7', '#0ea5e9', '#38bdf8'],
      collisionRadius: 0.2,
      heightM: 0.6,
      placementSurface: 'wall',
      stackable: false,
      maxStackCount: 1,
      weightKg: 7.5,
    },
    {
      name: 'Cable Conduit Bundle',
      propType: 'cable_bundle',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#0f172a', '#1e293b', '#f59e0b'],
      collisionRadius: 0.18,
      heightM: 0.1,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 6.0,
    },
  ],

  victorian_parlor: [
    {
      name: 'Ornate Brass Table Candelabra',
      propType: 'candelabra',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#d4af37', '#cd7f32', '#b8860b'],
      collisionRadius: 0.15,
      heightM: 0.48,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 3.8,
    },
    {
      name: 'Antique Leatherbound Tome',
      propType: 'antique_book',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#581c1c', '#2d1810', '#1b3817'],
      collisionRadius: 0.16,
      heightM: 0.06,
      placementSurface: 'tabletop',
      stackable: true,
      maxStackCount: 6,
      weightKg: 1.4,
    },
    {
      name: 'Fine Porcelain Tea Set',
      propType: 'porcelain_tea',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#f8fafc', '#e2e8f0', '#fef08a'],
      collisionRadius: 0.2,
      heightM: 0.15,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 1.2,
    },
    {
      name: 'Carved Walnut Side Table',
      propType: 'side_table',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#3e2723', '#4e342e', '#2e1c14'],
      collisionRadius: 0.3,
      heightM: 0.72,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 11.0,
    },
    {
      name: 'Velvet Chaise Lounge',
      propType: 'chaise_lounge',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#831843', '#701a75', '#1e3a8a'],
      collisionRadius: 0.55,
      heightM: 0.85,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 32.0,
    },
    {
      name: 'Gilded Wall Portrait Frame',
      propType: 'wall_portrait',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#d4af37', '#b45309'],
      collisionRadius: 0.25,
      heightM: 0.9,
      placementSurface: 'wall',
      stackable: false,
      maxStackCount: 1,
      weightKg: 6.0,
    },
    {
      name: 'Grandfather Clock',
      propType: 'grandfather_clock',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#3e2723', '#2e1c14'],
      collisionRadius: 0.32,
      heightM: 2.1,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 55.0,
    },
    {
      name: 'Persian Silk Floor Rug',
      propType: 'floor_rug',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#991b1b', '#1e3a8a', '#854d0e'],
      collisionRadius: 0.8,
      heightM: 0.02,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 9.0,
    },
  ],

  modern_soundstage: [
    {
      name: 'C-Stand 40-inch with Grip Arm',
      propType: 'c_stand',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#94a3b8', '#cbd5e1', '#1e293b'],
      collisionRadius: 0.35,
      heightM: 1.75,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 9.2,
    },
    {
      name: 'Full Apple Box Set',
      propType: 'apple_box',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#d4b886', '#bfa069', '#1e293b'],
      collisionRadius: 0.25,
      heightM: 0.2,
      placementSurface: 'floor',
      stackable: true,
      maxStackCount: 4,
      weightKg: 4.5,
    },
    {
      name: 'Heavy Duty 25lb Sandbag',
      propType: 'sandbag',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#eab308', '#ca8a04', '#1e293b'],
      collisionRadius: 0.2,
      heightM: 0.12,
      placementSurface: 'floor',
      stackable: true,
      maxStackCount: 3,
      weightKg: 11.3,
    },
    {
      name: 'BNC / SDI Cable Loom',
      propType: 'cable_loom',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#e11d48', '#2563eb', '#16a34a'],
      collisionRadius: 0.25,
      heightM: 0.08,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 5.5,
    },
    {
      name: 'Wireless Production Director Monitor',
      propType: 'director_monitor',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#0f172a', '#1e293b', '#334155'],
      collisionRadius: 0.28,
      heightM: 0.4,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 6.8,
    },
    {
      name: 'Grip Production Sound Cart',
      propType: 'sound_cart',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#334155', '#1e293b', '#0f172a'],
      collisionRadius: 0.45,
      heightM: 1.1,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 28.0,
    },
    {
      name: 'Clapperboard Slate',
      propType: 'clapperboard',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#ffffff', '#000000'],
      collisionRadius: 0.15,
      heightM: 0.25,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 0.8,
    },
    {
      name: 'Director Folding Viewfinder Stand',
      propType: 'viewfinder_stand',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#475569', '#0f172a'],
      collisionRadius: 0.3,
      heightM: 1.4,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 4.2,
    },
  ],

  cyberpunk_alley: [
    {
      name: 'Neon Hologram Sign Kaneda',
      propType: 'neon_sign',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#ec4899', '#06b6d4', '#a855f7'],
      collisionRadius: 0.3,
      heightM: 0.7,
      placementSurface: 'wall',
      stackable: false,
      maxStackCount: 1,
      weightKg: 8.5,
    },
    {
      name: 'Industrial Waste Dumpster',
      propType: 'dumpster',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#166534', '#1e293b', '#374151'],
      collisionRadius: 0.65,
      heightM: 1.2,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 75.0,
    },
    {
      name: 'Cyberware Street Stall Table',
      propType: 'cyber_stall',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#1e293b', '#334155'],
      collisionRadius: 0.5,
      heightM: 0.85,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 22.0,
    },
    {
      name: 'Stacked Synthetic Circuit Crates',
      propType: 'circuit_crate',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#f59e0b', '#ef4444', '#10b981'],
      collisionRadius: 0.24,
      heightM: 0.28,
      placementSurface: 'floor',
      stackable: true,
      maxStackCount: 5,
      weightKg: 8.5,
    },
    {
      name: 'Overflowing Ramen Bowl & Chopsticks',
      propType: 'ramen_bowl',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#f87171', '#fef08a', '#ffffff'],
      collisionRadius: 0.1,
      heightM: 0.12,
      placementSurface: 'tabletop',
      stackable: false,
      maxStackCount: 1,
      weightKg: 0.7,
    },
    {
      name: 'High Voltage Steam Pipe Section',
      propType: 'steam_pipe',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#b45309', '#78350f', '#64748b'],
      collisionRadius: 0.2,
      heightM: 1.5,
      placementSurface: 'wall',
      stackable: false,
      maxStackCount: 1,
      weightKg: 32.0,
    },
    {
      name: 'Puddle with Neon Reflection Disc',
      propType: 'neon_puddle',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#06b6d4', '#ec4899', '#a855f7'],
      collisionRadius: 0.45,
      heightM: 0.01,
      placementSurface: 'floor',
      stackable: false,
      maxStackCount: 1,
      weightKg: 0.0,
    },
    {
      name: 'Surveillance CCTV Drone Dock',
      propType: 'drone_dock',
      defaultScale: { x: 1, y: 1, z: 1 },
      colorOptions: ['#0f172a', '#ef4444'],
      collisionRadius: 0.22,
      heightM: 0.45,
      placementSurface: 'wall',
      stackable: false,
      maxStackCount: 1,
      weightKg: 6.2,
    },
  ],

  custom: [],
};

// ---------------------------------------------------------------------------
// PRNG and Math Algorithms
// ---------------------------------------------------------------------------

/**
 * Deterministic 32-bit PRNG (Mulberry32).
 */
export function createMulberry32(seed: number): () => number {
  let s = (seed >>> 0) || 1;
  return function () {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Generates 2D Poisson disk / rejection sampled scatter points within bounds.
 */
export function generatePoissonScatter2D(
  bounds: { minX: number; maxX: number; minZ: number; maxZ: number },
  minDistance: number,
  count: number,
  seed: number,
): Array<{ x: number; z: number }> {
  const points: Array<{ x: number; z: number }> = [];
  if (count <= 0) return points;

  const width = Math.max(0.01, bounds.maxX - bounds.minX);
  const depth = Math.max(0.01, bounds.maxZ - bounds.minZ);
  const minDistSq = minDistance * minDistance;
  const rng = createMulberry32(seed);

  const maxAttempts = count * 40;
  let attempts = 0;

  while (points.length < count && attempts < maxAttempts) {
    attempts++;
    const candidateX = bounds.minX + rng() * width;
    const candidateZ = bounds.minZ + rng() * depth;

    let valid = true;
    for (let i = 0; i < points.length; i++) {
      const p = points[i];
      const dx = p.x - candidateX;
      const dz = p.z - candidateZ;
      if (dx * dx + dz * dz < minDistSq) {
        valid = false;
        break;
      }
    }

    if (valid) {
      points.push({ x: candidateX, z: candidateZ });
    }
  }

  return points;
}

/**
 * Extracts semantic scatter regions (floor, tabletops, walls/perimeters) from scene data.
 */
export function detectSemanticRegions(
  sceneData?: Partial<SceneData>,
  stageDimensions: { widthM: number; depthM: number; heightM: number } = {
    widthM: 10,
    depthM: 10,
    heightM: 4,
  },
): ScatterRegion[] {
  const regions: ScatterRegion[] = [];
  const halfW = stageDimensions.widthM * 0.5;
  const halfD = stageDimensions.depthM * 0.5;

  // 1. Primary Floor Region
  regions.push({
    id: 'region_floor_main',
    name: 'Main Stage Floor',
    type: 'floor',
    bounds: {
      min: { x: -halfW, y: 0, z: -halfD },
      max: { x: halfW, y: 0.1, z: halfD },
    },
  });

  // 2. Tabletop / Elevated Furniture Regions from existing scene props
  if (sceneData?.props && Array.isArray(sceneData.props)) {
    for (const p of sceneData.props) {
      const nameLower = (p.name || '').toLowerCase();
      const cat = (p.category || '').toLowerCase();
      const isTableLike =
        nameLower.includes('table') ||
        nameLower.includes('desk') ||
        nameLower.includes('bench') ||
        nameLower.includes('counter') ||
        nameLower.includes('cart') ||
        nameLower.includes('stand') ||
        nameLower.includes('crate') ||
        cat === 'furniture';

      if (isTableLike) {
        const sx = Math.max(0.4, (p.scale?.x ?? 1) * 0.8);
        const sz = Math.max(0.4, (p.scale?.z ?? 1) * 0.8);
        const sy = p.scale?.y ?? 0.8;
        const topY = p.position.y + sy;

        regions.push({
          id: `region_tabletop_${p.id}`,
          name: `${p.name || 'Prop'} Surface`,
          type: 'tabletop',
          anchorEntityId: p.id,
          bounds: {
            min: {
              x: p.position.x - sx * 0.5,
              y: topY,
              z: p.position.z - sz * 0.5,
            },
            max: {
              x: p.position.x + sx * 0.5,
              y: topY + 0.05,
              z: p.position.z + sz * 0.5,
            },
          },
        });
      }
    }
  }

  // 3. Wall / Perimeter Regions
  if (sceneData?.architecture?.walls && sceneData.architecture.walls.length > 0) {
    for (const w of sceneData.architecture.walls) {
      const minX = Math.min(w.start.x, w.end.x);
      const maxX = Math.max(w.start.x, w.end.x);
      const minZ = Math.min(w.start.y, w.end.y);
      const maxZ = Math.max(w.start.y, w.end.y);

      regions.push({
        id: `region_wall_${w.id}`,
        name: `Wall Segment ${w.id.slice(0, 6)}`,
        type: 'wall',
        anchorEntityId: w.id,
        bounds: {
          min: { x: minX - 0.2, y: 0, z: minZ - 0.2 },
          max: { x: maxX + 0.2, y: w.heightM || 3.0, z: maxZ + 0.2 },
        },
      });
    }
  } else {
    // Stage Perimeter Bounds (North, South, East, West)
    regions.push({
      id: 'region_perimeter_north',
      name: 'North Stage Perimeter',
      type: 'perimeter',
      bounds: {
        min: { x: -halfW, y: 0, z: -halfD },
        max: { x: halfW, y: stageDimensions.heightM, z: -halfD + 0.5 },
      },
    });
    regions.push({
      id: 'region_perimeter_south',
      name: 'South Stage Perimeter',
      type: 'perimeter',
      bounds: {
        min: { x: -halfW, y: 0, z: halfD - 0.5 },
        max: { x: halfW, y: stageDimensions.heightM, z: halfD },
      },
    });
    regions.push({
      id: 'region_perimeter_east',
      name: 'East Stage Perimeter',
      type: 'perimeter',
      bounds: {
        min: { x: halfW - 0.5, y: 0, z: -halfD },
        max: { x: halfW, y: stageDimensions.heightM, z: halfD },
      },
    });
    regions.push({
      id: 'region_perimeter_west',
      name: 'West Stage Perimeter',
      type: 'perimeter',
      bounds: {
        min: { x: -halfW, y: 0, z: -halfD },
        max: { x: -halfW + 0.5, y: stageDimensions.heightM, z: halfD },
      },
    });
  }

  return regions;

}

/**
 * Pure domain iterative impulse separation and gravitational settling solver.
 * Prevents prop overlaps, aligns props to surface normals, and resolves vertical stacking.
 */
export function simulatePhysicsImpulseSettling(
  items: SettledPropItem[],
  obstacles: BoundingBox3D[] = [],
  gravity: number = 9.81,
  iterations: number = 20,
): SettledPropItem[] {
  if (!items || items.length === 0) return [];

  // Deep clone items to ensure pure function behavior
  const settled: SettledPropItem[] = items.map((item) => ({
    ...item,
    position: { ...item.position },
    rotation: { ...item.rotation },
    scale: { ...item.scale },
    isSettled: false,
  }));

  const numItems = settled.length;

  for (let iter = 0; iter < iterations; iter++) {
    // 1. Planar 2D impulse separation & stacking resolution
    for (let i = 0; i < numItems; i++) {
      const a = settled[i];

      for (let j = i + 1; j < numItems; j++) {
        const b = settled[j];

        const dx = b.position.x - a.position.x;
        const dz = b.position.z - a.position.z;
        const distSq = dx * dx + dz * dz;
        const dist = Math.sqrt(distSq);

        // Approximate collision radius from scale and template
        const rA = Math.max(0.12, 0.35 * ((a.scale.x + a.scale.z) * 0.5));
        const rB = Math.max(0.12, 0.35 * ((b.scale.x + b.scale.z) * 0.5));
        const minDist = rA + rB;


        // If items are stacked on different vertical levels, skip horizontal separation
        if (a.stackLevel !== b.stackLevel) {
          continue;
        }

        const isStackable =
          a.propType === b.propType &&
          (a.propType.includes('crate') ||
            a.propType.includes('book') ||
            a.propType.includes('box') ||
            a.propType.includes('paper') ||
            a.propType.includes('stone'));

        const verticalOverlap = Math.abs(a.position.y - b.position.y) < 0.4;

        if (dist < minDist && verticalOverlap) {


          // Check stacking opportunity for identical / stackable items
          if (dist < minDist * 0.35 && isStackable && a.stackLevel === 0 && b.stackLevel === 0) {
            b.stackLevel = 1;
            b.position.x = a.position.x;
            b.position.z = a.position.z;
            b.position.y = a.position.y + Math.max(0.15, a.scale.y * 0.3);
            b.surfaceY = a.position.y;
            continue;
          }


          // Separation impulse

          const overlap = minDist - (dist || 0.001);
          const nx = dist > 0.001 ? dx / dist : 1;
          const nz = dist > 0.001 ? dz / dist : 0;

          const separationHalf = overlap * 0.5;
          a.position.x -= nx * separationHalf;
          a.position.z -= nz * separationHalf;
          b.position.x += nx * separationHalf;
          b.position.z += nz * separationHalf;
        }
      }
    }

    // 2. Obstacle boundary repulsion
    for (let i = 0; i < numItems; i++) {
      const item = settled[i];
      for (const obs of obstacles) {
        if (
          item.position.x >= obs.min.x &&
          item.position.x <= obs.max.x &&
          item.position.z >= obs.min.z &&
          item.position.z <= obs.max.z &&
          item.position.y >= obs.min.y &&
          item.position.y <= obs.max.y
        ) {
          // Push item to closest obstacle face
          const dMinX = item.position.x - obs.min.x;
          const dMaxX = obs.max.x - item.position.x;
          const dMinZ = item.position.z - obs.min.z;
          const dMaxZ = obs.max.z - item.position.z;

          const minPush = Math.min(dMinX, dMaxX, dMinZ, dMaxZ);
          if (minPush === dMinX) item.position.x = obs.min.x - 0.15;
          else if (minPush === dMaxX) item.position.x = obs.max.x + 0.15;
          else if (minPush === dMinZ) item.position.z = obs.min.z - 0.15;
          else item.position.z = obs.max.z + 0.15;
        }
      }
    }

    // 3. Gravitational downward settling
    for (let i = 0; i < numItems; i++) {
      const item = settled[i];
      const targetFloor = item.surfaceY + (item.stackLevel > 0 ? item.stackLevel * 0.25 : 0);
      if (item.position.y > targetFloor) {
        const fallStep = Math.min(item.position.y - targetFloor, (gravity / iterations) * 0.1);
        item.position.y -= fallStep;
      } else if (item.position.y < targetFloor) {
        item.position.y = targetFloor;
      }
    }
  }

  // Finalize settlement state
  for (const item of settled) {
    item.isSettled = true;
  }

  return settled;
}

/**
 * Generates fully dressed props according to the curated catalogs for the specified theme and region.
 */
export function generateThemeScatter(
  theme: ScatterTheme,
  region: ScatterRegion,
  config: GenerativeScatterConfig,
): SettledPropItem[] {
  const catalog = THEME_PROP_CATALOGS[theme] || THEME_PROP_CATALOGS.film_noir_office;
  if (!catalog || catalog.length === 0) return [];

  const surfaceType = region.type === 'tabletop' ? 'tabletop' : region.type === 'wall' || region.type === 'perimeter' ? 'wall' : 'floor';
  const matchingTemplates = catalog.filter(
    (t) => t.placementSurface === surfaceType || (surfaceType === 'floor' && t.placementSurface === 'tabletop' && t.stackable),
  );

  const pool = matchingTemplates.length > 0 ? matchingTemplates : catalog;
  const rng = createMulberry32(config.seed || 12345);

  const bWidth = Math.max(0.2, region.bounds.max.x - region.bounds.min.x);
  const bDepth = Math.max(0.2, region.bounds.max.z - region.bounds.min.z);
  const areaM2 = bWidth * bDepth;

  let targetCount = 5;
  if (config.density === 'sparse') {
    targetCount = Math.max(1, Math.round(areaM2 * 0.8));
  } else if (config.density === 'medium') {
    targetCount = Math.max(2, Math.round(areaM2 * 1.8));
  } else if (config.density === 'dense') {
    targetCount = Math.max(3, Math.round(areaM2 * 3.5));
  }

  targetCount = Math.min(targetCount, config.maxItems || 30);

  const scatterPoints = generatePoissonScatter2D(
    {
      minX: region.bounds.min.x + 0.1,
      maxX: region.bounds.max.x - 0.1,
      minZ: region.bounds.min.z + 0.1,
      maxZ: region.bounds.max.z - 0.1,
    },
    Math.max(0.15, config.minDistanceM || 0.4),
    targetCount,
    config.seed || 12345,
  );

  const baseSurfaceY = region.type === 'tabletop' ? region.bounds.min.y : config.groundY ?? 0;
  const generatedItems: SettledPropItem[] = [];

  for (let i = 0; i < scatterPoints.length; i++) {
    const pt = scatterPoints[i];
    const tmplIndex = Math.floor(rng() * pool.length);
    const tmpl = pool[tmplIndex];

    const color =
      tmpl.colorOptions.length > 0
        ? tmpl.colorOptions[Math.floor(rng() * tmpl.colorOptions.length)]
        : '#94a3b8';

    // Random yaw rotation (or wall-aligned normal)
    let rotY = rng() * Math.PI * 2;
    if (config.alignToWalls && (region.type === 'wall' || region.type === 'perimeter')) {
      rotY = Math.PI * 0.5;
    }

    const scaleVariance = 0.9 + rng() * 0.2;

    const item: SettledPropItem = {
      id: `prop_scatter_${theme}_${i}_${Math.random().toString(36).slice(2, 7)}`,
      templateName: tmpl.name,
      propType: tmpl.propType,
      name: `${tmpl.name} #${i + 1}`,
      position: {
        x: Number(pt.x.toFixed(3)),
        y: Number(baseSurfaceY.toFixed(3)),
        z: Number(pt.z.toFixed(3)),
      },
      rotation: {
        x: 0,
        y: Number(rotY.toFixed(3)),
        z: 0,
      },
      scale: {
        x: Number((tmpl.defaultScale.x * scaleVariance).toFixed(3)),
        y: Number((tmpl.defaultScale.y * scaleVariance).toFixed(3)),
        z: Number((tmpl.defaultScale.z * scaleVariance).toFixed(3)),
      },
      color,
      isSettled: false,
      stackLevel: 0,
      surfaceY: baseSurfaceY,
      weightKg: Number(tmpl.weightKg.toFixed(2)),
    };

    generatedItems.push(item);

  }

  if (config.enablePhysicsSettling && generatedItems.length > 0) {
    return simulatePhysicsImpulseSettling(generatedItems, [], 9.81, 20);
  }

  for (const it of generatedItems) {
    it.isSettled = true;
  }
  return generatedItems;
}

// ---------------------------------------------------------------------------
// Offline Deterministic NLP Command Parser
// ---------------------------------------------------------------------------

/**
 * Offline deterministic natural language command parser.
 * Interprets set dressing, prop, lighting, and atmosphere commands without requiring an external API key.
 */
export function parseDeterministicNlCommand(
  command: string,
  _currentScene?: Partial<SceneData>,
): GeminiAiSceneMutation[] {
  const mutations: GeminiAiSceneMutation[] = [];
  const normalized = (command || '').trim().toLowerCase();
  if (!normalized) return mutations;

  // 1. Theme Scatter commands
  if (
    normalized.includes('scatter') ||
    normalized.includes('dress') ||
    normalized.includes('populate') ||
    normalized.includes('fill')
  ) {
    let theme: ScatterTheme = 'modern_soundstage';
    if (normalized.includes('noir') || normalized.includes('office') || normalized.includes('detective')) {
      theme = 'film_noir_office';
    } else if (normalized.includes('sci-fi') || normalized.includes('corridor') || normalized.includes('cyber') && normalized.includes('corridor')) {
      theme = 'sci_fi_corridor';
    } else if (normalized.includes('victorian') || normalized.includes('parlor') || normalized.includes('antique') || normalized.includes('classic')) {
      theme = 'victorian_parlor';
    } else if (normalized.includes('cyberpunk') || normalized.includes('alley') || normalized.includes('neon') || normalized.includes('street')) {
      theme = 'cyberpunk_alley';
    } else if (normalized.includes('soundstage') || normalized.includes('stage') || normalized.includes('studio') || normalized.includes('film')) {
      theme = 'modern_soundstage';
    }

    let density: ScatterDensity = 'medium';
    if (normalized.includes('dense') || normalized.includes('heavy') || normalized.includes('lot of')) {
      density = 'dense';
    } else if (normalized.includes('sparse') || normalized.includes('few') || normalized.includes('minimal')) {
      density = 'sparse';
    }

    mutations.push({
      action: 'scatter_theme',
      parameters: {
        theme,
        density,
        enablePhysicsSettling: true,
      },
      explanation: `Generatively scattered ${density} set dressing props tailored for ${theme.replace(/_/g, ' ')}.`,
    });
  }

  // 2. Lighting Modifications (Color / Kelvin / Intensity)
  if (
    normalized.includes('light') ||
    normalized.includes('kelvin') ||
    normalized.includes('dim') ||
    normalized.includes('bright')
  ) {
    const lightParams: Record<string, any> = {};

    // Color extraction
    if (normalized.includes('red')) lightParams.colorHex = '#ef4444';
    else if (normalized.includes('blue')) lightParams.colorHex = '#3b82f6';
    else if (normalized.includes('amber') || normalized.includes('warm') || normalized.includes('golden')) {
      lightParams.colorHex = '#f59e0b';
      lightParams.kelvin = 3200;
    } else if (normalized.includes('cool') || normalized.includes('daylight')) {
      lightParams.colorHex = '#38bdf8';
      lightParams.kelvin = 5600;
    } else if (normalized.includes('green')) lightParams.colorHex = '#10b981';
    else if (normalized.includes('purple') || normalized.includes('magenta') || normalized.includes('pink')) {
      lightParams.colorHex = '#d946ef';
    } else if (normalized.includes('cyan') || normalized.includes('teal')) {
      lightParams.colorHex = '#06b6d4';
    }

    // Kelvin parsing e.g. "3200k" or "5600"
    const kelvinMatch = normalized.match(/(\d{4})\s*k?/);
    if (kelvinMatch) {
      const k = parseInt(kelvinMatch[1], 10);
      if (k >= 1500 && k <= 10000) lightParams.kelvin = k;
    }

    // Intensity parsing
    const boostMatch = normalized.match(/(?:boost|increase|raise|turn up)\s+(?:.*?)(\d+)%/);
    const dimMatch = normalized.match(/(?:dim|decrease|lower|turn down)\s+(?:.*?)(\d+)%/);
    if (boostMatch) {
      lightParams.intensityMultiplier = Number((1 + parseInt(boostMatch[1], 10) / 100).toFixed(2));
    } else if (dimMatch) {
      lightParams.intensityMultiplier = Number((Math.max(0.1, 1 - parseInt(dimMatch[1], 10) / 100)).toFixed(2));
    } else if (normalized.includes('dim')) {
      lightParams.intensityMultiplier = 0.5;
    } else if (normalized.includes('bright') || normalized.includes('boost')) {
      lightParams.intensityMultiplier = 1.5;
    }

    mutations.push({
      action: 'modify_lighting',
      parameters: lightParams,
      explanation: `Adjusted scene lighting parameters: ${JSON.stringify(lightParams)}.`,
    });
  }

  // 3. Atmosphere / Fog Modifications
  if (
    normalized.includes('fog') ||
    normalized.includes('atmosphere') ||
    normalized.includes('haze') ||
    normalized.includes('smoke') ||
    (normalized.includes('clear') && (normalized.includes('sky') || normalized.includes('fog') || normalized.includes('air')))
  ) {
    const atmosParams: Record<string, any> = {};

    if (normalized.includes('clear')) {
      atmosParams.enabled = false;
      atmosParams.density = 0.0;
    } else {
      atmosParams.enabled = true;
      if (normalized.includes('dense') || normalized.includes('heavy') || normalized.includes('thick')) {
        atmosParams.density = 0.65;
      } else if (normalized.includes('light') || normalized.includes('subtle') || normalized.includes('slight')) {
        atmosParams.density = 0.15;
      } else {
        atmosParams.density = 0.35;
      }

      if (normalized.includes('blue')) atmosParams.colorHex = '#1e3a8a';
      else if (normalized.includes('red')) atmosParams.colorHex = '#7f1d1d';
      else if (normalized.includes('amber') || normalized.includes('warm')) atmosParams.colorHex = '#78350f';
      else if (normalized.includes('cyan')) atmosParams.colorHex = '#083344';
      else if (normalized.includes('purple')) atmosParams.colorHex = '#581c87';
    }

    mutations.push({
      action: 'modify_atmosphere',
      parameters: atmosParams,
      explanation: `Modified atmospheric simulation density and color palette.`,
    });
  }

  // 4. Specific Prop Additions (e.g. "add 3 c-stands", "add apple box", "add desk")
  const addPropMatch = normalized.match(/(?:add|place|spawn|put)\s+(\d+)?\s*([a-z0-9_\-\s]+)/i);
  if (addPropMatch && !normalized.includes('scatter') && !normalized.includes('dress') && !normalized.includes('smoke') && !normalized.includes('fog') && !normalized.includes('haze')) {
    const count = addPropMatch[1] ? Math.min(10, parseInt(addPropMatch[1], 10)) : 1;
    const propNameQuery = addPropMatch[2].trim();

    mutations.push({
      action: 'add_prop',
      parameters: {
        propName: propNameQuery,
        count,
        position: { x: 0, y: 0, z: 0 },
      },
      explanation: `Spawned ${count}x "${propNameQuery}" prop instance(s) into scene.`,
    });
  }

  // 5. Prop Removal commands
  if (normalized.includes('remove') || normalized.includes('delete') || normalized.includes('clear')) {
    mutations.push({
      action: 'remove_prop',
      parameters: {
        query: normalized.replace(/remove|delete|clear|all|from the desk|from table|from floor/g, '').trim(),
      },
      explanation: `Removed matching props from scene graph.`,
    });
  }

  return mutations;
}

// ---------------------------------------------------------------------------
// Gemini AI Omni Set Director Integration
// ---------------------------------------------------------------------------

/**
 * Builds a structured Gemini AI system prompt incorporating SetView's scene schema.
 */
export function buildGeminiAiSystemPrompt(sceneData: Partial<SceneData>, userInstruction?: string): string {
  const sceneSummary = {
    sceneName: sceneData.name || 'Untitled Scene',
    actorCount: sceneData.actors?.length || 0,
    cameraCount: sceneData.cameras?.length || 0,
    lightCount: sceneData.lights?.length || 0,
    propCount: sceneData.props?.length || 0,
    atmosphere: sceneData.atmosphere ? { enabled: sceneData.atmosphere.enabled, density: sceneData.atmosphere.density } : null,
    setDressing: sceneData.setDressing ? {
      activeTheme: sceneData.setDressing.activeTheme,
      settledItemsCount: sceneData.setDressing.settledItems?.length || 0,
    } : null,
  };

  let prompt = `You are the Gemini AI Omni Set Director for SetView, an AR/WebXR virtual production and shot blocking suite.
Your role is to interpret director instructions and return strict JSON mutation commands for 3D props, set dressing, lighting, and volumetric atmosphere.

CURRENT SCENE STATE:
${JSON.stringify(sceneSummary, null, 2)}

SUPPORTED THEMES:
- 'film_noir_office'
- 'sci_fi_corridor'
- 'victorian_parlor'
- 'modern_soundstage'
- 'cyberpunk_alley'
`;

  if (userInstruction) {
    prompt += `\nDIRECTOR INSTRUCTION:\n${userInstruction}\n`;
  }

  prompt += `
SUPPORTED ACTIONS:
1. 'scatter_theme': { theme: string, density: 'sparse'|'medium'|'dense', alignToWalls: boolean, enablePhysicsSettling: boolean }
2. 'add_prop': { propName: string, propType: string, position: {x,y,z}, scale: {x,y,z}, color: string, count: number }
3. 'update_prop': { propId: string, updates: object }
4. 'remove_prop': { query: string, propId?: string }
5. 'modify_lighting': { colorHex?: string, kelvin?: number, intensityMultiplier?: number }
6. 'modify_atmosphere': { enabled?: boolean, density?: number, colorHex?: string }
7. 'batch_mutate': { mutations: GeminiAiSceneMutation[] }

RESPONSE FORMAT:
You MUST respond with a valid JSON array of GeminiAiSceneMutation objects:
[
  {
    "action": "scatter_theme",
    "parameters": { "theme": "film_noir_office", "density": "medium" },
    "explanation": "Scattered vintage noir props on desks and floors."
  }
]
`;

  return prompt;
}

/**
 * Validates, cleans, and parses Gemini AI JSON response.
 */
export function parseGeminiAiResponse(rawJsonOrText: string, fallbackInstruction?: string): GeminiAiSceneMutation[] {
  if (!rawJsonOrText || typeof rawJsonOrText !== 'string') return [];

  let cleanText = rawJsonOrText.trim();
  // Strip Markdown JSON code fences if present
  if (cleanText.startsWith('```')) {
    cleanText = cleanText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
  }

  try {
    const parsed = JSON.parse(cleanText);
    const list = Array.isArray(parsed) ? parsed : [parsed];
    const mutations: GeminiAiSceneMutation[] = [];

    for (const item of list) {
      if (item && typeof item === 'object' && typeof item.action === 'string') {
        mutations.push({
          action: item.action,
          parameters: item.parameters || {},
          explanation: item.explanation || `Executed ${item.action}`,
        });
      }
    }

    if (mutations.length > 0) return mutations;
  } catch (_e) {
    // If JSON parsing fails, fall back to deterministic NLP
  }

  return parseDeterministicNlCommand(fallbackInstruction || rawJsonOrText);
}


/**
 * Atomically applies AI mutation batch to SceneData.
 */
export function applyAiMutationsToScene(
  sceneData: SceneData,
  mutations: GeminiAiSceneMutation[],
): { success: boolean; appliedCount: number; messages: string[] } {
  if (!sceneData || !Array.isArray(mutations)) {
    return { success: false, appliedCount: 0, messages: ['Invalid scene data or mutation array'] };
  }

  let appliedCount = 0;
  const messages: string[] = [];

  for (const m of mutations) {
    switch (m.action) {
      case 'scatter_theme': {
        const theme: ScatterTheme = m.parameters.theme || 'modern_soundstage';
        const density: ScatterDensity = m.parameters.density || 'medium';

        if (!sceneData.setDressing) {
          sceneData.setDressing = createSetDressingConfig();
        }

        sceneData.setDressing.activeTheme = theme;
        sceneData.setDressing.scatterConfig.theme = theme;
        sceneData.setDressing.scatterConfig.density = density;

        const regions = detectSemanticRegions(sceneData);
        sceneData.setDressing.regions = regions;

        const newItems: SettledPropItem[] = [];
        for (const region of regions) {
          const items = generateThemeScatter(theme, region, sceneData.setDressing.scatterConfig);
          newItems.push(...items);
        }

        sceneData.setDressing.settledItems = newItems;
        appliedCount++;
        messages.push(`Scattered ${newItems.length} props for theme "${theme}"`);
        break;
      }

      case 'modify_lighting': {
        if (!sceneData.lights) sceneData.lights = [];
        for (const l of sceneData.lights) {
          if (m.parameters.kelvin !== undefined) l.colorKelvin = m.parameters.kelvin;
          if (m.parameters.intensityMultiplier !== undefined) {
            l.intensity = Number((l.intensity * m.parameters.intensityMultiplier).toFixed(2));
          }
        }
        appliedCount++;
        messages.push(`Updated ${sceneData.lights.length} scene light(s)`);
        break;
      }

      case 'modify_atmosphere': {
        if (!sceneData.atmosphere) {
          sceneData.atmosphere = {
            enabled: true,
            preset: 'subtle_haze',
            density: 0.3,
            tintHex: '#ffffff',
            scatteringFactor: 0.7,
            heightFalloff: 0.5,
            dustMotesCount: 200,
            beamIntensity: 1.0,
          };
        }
        if (m.parameters.enabled !== undefined) sceneData.atmosphere.enabled = m.parameters.enabled;
        if (m.parameters.density !== undefined) sceneData.atmosphere.density = m.parameters.density;
        if (m.parameters.colorHex !== undefined) sceneData.atmosphere.tintHex = m.parameters.colorHex;
        appliedCount++;
        messages.push(`Updated atmospheric parameters`);
        break;
      }


      case 'add_prop': {
        if (!sceneData.props) sceneData.props = [];
        const count = m.parameters.count || 1;
        for (let i = 0; i < count; i++) {
          const newProp: PropData = {
            id: `prop_ai_${Date.now()}_${i}`,
            assetId: m.parameters.propType || 'custom_prop',
            name: m.parameters.propName || `AI Prop #${sceneData.props.length + 1}`,
            category: 'set_dressing',
            position: m.parameters.position || { x: (i - count / 2) * 0.5, y: 0, z: 0 },
            rotationY: 0,
            scale: m.parameters.scale || { x: 1, y: 1, z: 1 },
            colorHex: m.parameters.color || '#3b82f6',
            sourceType: 'procedural',
          };
          sceneData.props.push(newProp);
        }
        appliedCount++;
        messages.push(`Added ${count} prop instance(s)`);
        break;
      }

      case 'remove_prop': {
        if (!sceneData.props) break;
        const query = (m.parameters.query || '').toLowerCase();
        const initialCount = sceneData.props.length;
        sceneData.props = sceneData.props.filter((p) => !p.name.toLowerCase().includes(query));
        const removed = initialCount - sceneData.props.length;
        appliedCount++;
        messages.push(`Removed ${removed} matching prop(s)`);
        break;
      }

      default:
        break;
    }
  }

  return {
    success: appliedCount > 0,
    appliedCount,
    messages,
  };
}

// ---------------------------------------------------------------------------
// Manifest Generators and Exporters
// ---------------------------------------------------------------------------

/**
 * Generates an RFC 4180 CSV manifest export of settled set dressing props.
 */
export function generateSetDressingManifestCsv(manifest: SetDressingManifest): string {
  const lines: string[] = [];
  lines.push('ItemId,TemplateName,PropType,Name,PosX,PosY,PosZ,RotX,RotY,RotZ,ScaleX,ScaleY,ScaleZ,Color,StackLevel,SurfaceY,IsSettled');

  for (const item of manifest.items) {
    const row = [
      `"${item.id}"`,
      `"${item.templateName.replace(/"/g, '""')}"`,
      `"${item.propType}"`,
      `"${item.name.replace(/"/g, '""')}"`,
      item.position.x.toFixed(3),
      item.position.y.toFixed(3),
      item.position.z.toFixed(3),
      item.rotation.x.toFixed(3),
      item.rotation.y.toFixed(3),
      item.rotation.z.toFixed(3),
      item.scale.x.toFixed(3),
      item.scale.y.toFixed(3),
      item.scale.z.toFixed(3),
      `"${item.color}"`,
      item.stackLevel,
      item.surfaceY.toFixed(3),
      item.isSettled ? 'TRUE' : 'FALSE',
    ];
    lines.push(row.join(','));
  }

  return lines.join('\r\n');
}

/**
 * Generates a standalone HTML Set Dressing Deck with top-down SVG diagram.
 */
export function generateSetDressingDeckHtml(
  manifest: SetDressingManifest,
  sceneName: string = 'Virtual Stage',
): string {
  const svgElements: string[] = [];
  const svgWidth = 600;
  const svgHeight = 600;
  const centerPx = 300;
  const scalePxPerM = 40;

  // Grid background
  svgElements.push(
    `<rect x="0" y="0" width="${svgWidth}" height="${svgHeight}" fill="#0f172a" stroke="#1e293b" stroke-width="2"/>`,
  );

  // Stage boundaries (-6m to +6m)
  svgElements.push(
    `<rect x="${centerPx - 5 * scalePxPerM}" y="${centerPx - 5 * scalePxPerM}" width="${10 * scalePxPerM}" height="${10 * scalePxPerM}" fill="none" stroke="#334155" stroke-dasharray="4,4" stroke-width="1.5"/>`,
  );

  // Plot Settled Props
  for (const it of manifest.items) {
    const px = centerPx + it.position.x * scalePxPerM;
    const py = centerPx + it.position.z * scalePxPerM;
    const radius = Math.max(4, 0.25 * scalePxPerM);

    svgElements.push(
      `<circle cx="${px.toFixed(1)}" cy="${py.toFixed(1)}" r="${radius.toFixed(1)}" fill="${it.color}" fill-opacity="0.85" stroke="#ffffff" stroke-width="1"><title>${it.name} (${it.templateName})</title></circle>`,
    );
  }

  const rows = manifest.items
    .map(
      (it) => `
    <tr>
      <td><code>${it.id.slice(0, 8)}</code></td>
      <td><strong>${it.name}</strong></td>
      <td><span class="badge" style="background:${it.color}; color:#fff;">${it.templateName}</span></td>
      <td>[${it.position.x.toFixed(2)}, ${it.position.y.toFixed(2)}, ${it.position.z.toFixed(2)}]</td>
      <td>${it.stackLevel > 0 ? `Level ${it.stackLevel}` : 'Ground'}</td>
      <td><span class="status-pill ${it.isSettled ? 'settled' : 'unsettled'}">${it.isSettled ? 'Settled' : 'Dynamic'}</span></td>
    </tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>SetView Virtual Set Dressing Deck - ${sceneName}</title>
  <style>
    :root {
      --bg: #0b0f19;
      --card-bg: #131b2e;
      --text: #f8fafc;
      --text-muted: #94a3b8;
      --accent: #38bdf8;
      --border: #1e293b;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      margin: 0;
      padding: 32px;
      line-height: 1.5;
    }
    .header {
      margin-bottom: 24px;
      border-bottom: 1px solid var(--border);
      padding-bottom: 16px;
    }
    .header h1 {
      margin: 0 0 8px 0;
      color: var(--accent);
      font-size: 26px;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 16px;
      margin-bottom: 24px;
    }
    .stat-card {
      background: var(--card-bg);
      padding: 16px;
      border-radius: 8px;
      border: 1px solid var(--border);
    }
    .stat-label {
      font-size: 12px;
      color: var(--text-muted);
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .stat-value {
      font-size: 22px;
      font-weight: bold;
      color: var(--text);
      margin-top: 4px;
    }
    .diagram-container {
      background: var(--card-bg);
      padding: 20px;
      border-radius: 8px;
      border: 1px solid var(--border);
      margin-bottom: 24px;
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    svg {
      border-radius: 6px;
      max-width: 100%;
      height: auto;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      background: var(--card-bg);
      border-radius: 8px;
      overflow: hidden;
      border: 1px solid var(--border);
    }
    th, td {
      padding: 10px 14px;
      text-align: left;
      border-bottom: 1px solid var(--border);
      font-size: 13px;
    }
    th {
      background: #1e293b;
      color: var(--text-muted);
      font-weight: 600;
    }
    .badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: bold;
    }
    .status-pill {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 12px;
      font-size: 11px;
      font-weight: bold;
    }
    .status-pill.settled {
      background: rgba(16, 185, 129, 0.2);
      color: #10b981;
    }
    .status-pill.unsettled {
      background: rgba(245, 158, 11, 0.2);
      color: #f59e0b;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>SetView Virtual Set Dressing & AI Scatter Deck</h1>
    <p style="color: var(--text-muted); margin: 0;">Scene: <strong>${sceneName}</strong> | Generated: ${manifest.generatedAt}</p>
  </div>

  <div class="stats-grid">
    <div class="stat-card">
      <div class="stat-label">Active Theme</div>
      <div class="stat-value">${manifest.theme.replace(/_/g, ' ').toUpperCase()}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Total Placed Props</div>
      <div class="stat-value">${manifest.totalItems ?? manifest.totalItemCount ?? manifest.items.length}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Bounding Volume</div>
      <div class="stat-value">${(manifest.boundingVolumeM3 ?? 0).toFixed(1)} m³</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Total Mass</div>
      <div class="stat-value">${(manifest.totalWeightKg ?? 0).toFixed(1)} kg</div>
    </div>
  </div>


  <div class="diagram-container">
    <h3 style="margin-top:0; color:var(--accent);">Top-Down 2D Spatial Scatter Layout</h3>
    <svg width="${svgWidth}" height="${svgHeight}" viewBox="0 0 ${svgWidth} ${svgHeight}">
      ${svgElements.join('\n      ')}
    </svg>
  </div>

  <h3 style="color: var(--accent);">Procurement & Set Dressing Inventory</h3>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Prop Instance</th>
        <th>Template Archetype</th>
        <th>Position [X, Y, Z]</th>
        <th>Stack Level</th>
        <th>Physics State</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Factory & Normalization Functions
// ---------------------------------------------------------------------------

export function createDefaultScatterConfig(
  partial?: Partial<GenerativeScatterConfig>,
): GenerativeScatterConfig {
  return {
    theme: partial?.theme ?? 'film_noir_office',
    density: partial?.density ?? 'medium',
    minDistanceM: partial?.minDistanceM ?? 0.35,
    seed: partial?.seed ?? 42,
    alignToWalls: partial?.alignToWalls ?? true,
    enablePhysicsSettling: partial?.enablePhysicsSettling ?? true,
    groundY: partial?.groundY ?? 0.0,
    maxItems: partial?.maxItems ?? 35,
    customPrompt: partial?.customPrompt ?? '',
  };
}

export function createDefaultAiConfig(
  partial?: Partial<GeminiAiConfig>,
): GeminiAiConfig {
  return {
    apiKey: partial?.apiKey ?? '',
    model: partial?.model ?? 'gemini-2.5-flash',
    systemInstruction: partial?.systemInstruction ?? 'You are the Virtual Set Director for SetView.',
    temperature: partial?.temperature ?? 0.4,
  };
}

export function createSetDressingConfig(
  partial?: Partial<SetDressingConfig>,
): SetDressingConfig {
  return {
    enabled: partial?.enabled ?? true,
    activeTheme: partial?.activeTheme ?? 'film_noir_office',
    scatterConfig: createDefaultScatterConfig(partial?.scatterConfig),
    aiConfig: createDefaultAiConfig(partial?.aiConfig),
    regions: Array.isArray(partial?.regions) ? [...partial.regions] : [],
    settledItems: Array.isArray(partial?.settledItems) ? [...partial.settledItems] : [],
  };
}

export function isSetDressingConfig(val: unknown): val is SetDressingConfig {
  if (!val || typeof val !== 'object') return false;
  const c = val as SetDressingConfig;
  return (
    typeof c.enabled === 'boolean' &&
    typeof c.activeTheme === 'string' &&
    typeof c.scatterConfig === 'object' &&
    typeof c.aiConfig === 'object' &&
    Array.isArray(c.regions) &&
    Array.isArray(c.settledItems)
  );
}

export function normalizeSetDressingConfig(val: unknown): SetDressingConfig {
  if (!val || typeof val !== 'object') return createSetDressingConfig();
  const raw = val as Partial<SetDressingConfig>;
  return createSetDressingConfig(raw);
}
